### ISSUE TITLE
LoadError: Unable to locate CPLEX installation - windows 10

### ISSUE THREAD

**Issue by parsafard** [JuliaOpt/CPLEX.jl#106]
Hi,

I have installed cplex_studio127.win-x86-64 and julia-0.5.0-win64 on Windows 10. The Environment variables are set by CPLEX, but I still get the LoadError: Unable to locate CPLEX installation. Please let me know if you have any suggestions. 

Thanks,

**Comment by blegat** [comment]
Looking at the build script, the relevant part is [here](https://github.com/JuliaOpt/CPLEX.jl/blob/0fa0c7768a1c985fbdeb2d511a725ab40a104e7f/deps/build.jl#L29-L44).

Could you try to debug that part by running `Pkg.build("CPLEX")` and see what you get ?
For instance, what do you get if you run `@show ENV` ? Do you enter `if haskey(ENV,env)` ?

**Comment by mlubin** [comment]
12.7 was never tested on windows, the build script may not be correct

**Comment by parsafard** [comment]
Yesterday I revised the build script my self by adding "1270", but it did not work. After you changed it, I removed CPLEX and its folder and tried to build CPLEX again, but still got the same error. However, when I open the build script, it is not updated to the new one?

@show ENV
ENV = =C:=C:\WINDOWS\system32
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\mpars\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-BNKBM42
ComSpec=C:\WINDOWS\system32\cmd.exe
CPLEX_STUDIO_BINARIES127=C:\Program Files\IBM\ILOG\CPLEX_Studio127\cplex\bin\x64_win64;C:\Program Files\IBM\ILOG\CPLEX_Studio127\opl\bin\x64_win64;C:\Program Files\IBM\ILOG\CPLEX_Studio127\opl\oplide\;C:\Program Files\IBM\ILOG\CPLEX_Studio127\cpoptimizer\bin\x64_win64;C:\Program Files\IBM\ILOG\CPLEX_Studio127\opl\oplide\plugins\ilog.odms.ide.opllang.win32.win32.x86_64_12.7.0.0
CPLEX_STUDIO_DIR127=C:\Program Files\IBM\ILOG\CPLEX_Studio127
GUROBI_HOME=C:\gurobi650\win64
HOMEDRIVE=C:
HOMEPATH=\Users\mpars
LOCALAPPDATA=C:\Users\mpars\AppData\Local
LOGONSERVER=\\DESKTOP-BNKBM42
MOZ_PLUGIN_PATH=C:\Program Files (x86)\Foxit Software\Foxit Reader\plugins\
NUMBER_OF_PROCESSORS=4
OneDrive=C:\Users\mpars\OneDrive
OPENBLAS_MAIN_FREE=1
OS=Windows_NT
Path=C:\julia\bin;C:\Program Files\IBM\ILOG\CPLEX_Studio127\cplex\bin\x64_win64;C:\Program Files\IBM\ILOG\CPLEX_Studio127\opl\bin\x64_win64;C:\Program Files\IBM\ILOG\CPLEX_Studio127\opl\oplide\;C:\Program Files\IBM\ILOG\CPLEX_Studio127\cpoptimizer\bin\x64_win64;C:\Program Files\IBM\ILOG\CPLEX_Studio127\opl\oplide\plugins\ilog.odms.ide.opllang.win32.win32.x86_64_12.7.0.0;C:\gurobi650\win64\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\IBM\ILOG\CPLEX_Studio127\cplex\bin\x64_win64;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\mpars\Anaconda3;C:\Users\mpars\Anaconda3\Scripts;C:\Users\mpars\Anaconda3\Library\bin;C:\julia\bin;C:\Users\mpars\AppData\Local\atom\bin;C:\Users\mpars\AppData\Local\Microsoft\WindowsApps;C:\Program Files\IBM\ILOG\CPLEX_Studio127\cplex\bin\x64_win64
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=8e09
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\mpars\AppData\Local\Temp
TMP=C:\Users\mpars\AppData\Local\Temp
USERDOMAIN=DESKTOP-BNKBM42
USERDOMAIN_ROAMINGPROFILE=DESKTOP-BNKBM42
USERNAME=mpars
USERPROFILE=C:\Users\mpars
windir=C:\WINDOWS

Base.EnvHash with 42 entries:
  "=C:"                      => "C:\\WINDOWS\\system32"
  "ALLUSERSPROFILE"          => "C:\\ProgramData"
  "APPDATA"                  => "C:\\Users\\mpars\\AppData\\Roaming"
  "CommonProgramFiles"       => "C:\\Program Files\\Common Files"
  "CommonProgramFiles(x86)"  => "C:\\Program Files (x86)\\Common Files"
  "CommonProgramW6432"       => "C:\\Program Files\\Common Files"
  "COMPUTERNAME"             => "DESKTOP-BNKBM42"
  "ComSpec"                  => "C:\\WINDOWS\\system32\\cmd.exe"
  "CPLEX_STUDIO_BINARIES127" => "C:\\Program Files\\IBM\\ILOG\\CPLEX_Studio127\\cplex\\bin\\x64_win64;C:\\Program Files…
  "CPLEX_STUDIO_DIR127"      => "C:\\Program Files\\IBM\\ILOG\\CPLEX_Studio127"
  "GUROBI_HOME"              => "C:\\gurobi650\\win64"
  "HOMEDRIVE"                => "C:"
  "HOMEPATH"                 => "\\Users\\mpars"
  "LOCALAPPDATA"             => "C:\\Users\\mpars\\AppData\\Local"
  "LOGONSERVER"              => "\\\\DESKTOP-BNKBM42"
  "MOZ_PLUGIN_PATH"          => "C:\\Program Files (x86)\\Foxit Software\\Foxit Reader\\plugins\\"
  "NUMBER_OF_PROCESSORS"     => "4"
  "OneDrive"                 => "C:\\Users\\mpars\\OneDrive"
  "OPENBLAS_MAIN_FREE"       => "1"
  "OS"                       => "Windows_NT"
  "Path"                     => "C:\\julia\\bin;C:\\Program Files\\IBM\\ILOG\\CPLEX_Studio127\\cplex\\bin\\x64_win64;C:…
  "PATHEXT"                  => ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"
  "PROCESSOR_ARCHITECTURE"   => "AMD64"
  "PROCESSOR_IDENTIFIER"     => "Intel64 Family 6 Model 142 Stepping 9, GenuineIntel"
  "PROCESSOR_LEVEL"          => "6"
  ⋮                          => ⋮

**Comment by parsafard** [comment]
convert
cplex
cplex1270.dll
cplex1270processtransport.dll
cplex1270processworker.dll
cplex1270remote.dll
cplex1270remotejni.dll
cplex1270tcpiptransport.dll
cplex1270tcpipworker.dll
cplexamp
ILOG.Concert.dll
ILOG.Concert
ILOG.CPLEX.dll
ILOG.CPLEX

**Comment by parsafard** [comment]
I removed CPLEX from \.julia\v0.5\.cache and \.julia\v0.5\.metadata to reinstall it with new build.jl, but now I am getting the new error. 

ERROR: unknown package CPLEX
 in macro expansion at .\pkg\entry.jl:53 [inlined]
 in (::Base.Pkg.Entry.##2#5{String,Base.Pkg.Types.VersionSet})() at .\task.jl:360
 in sync_end() at .\task.jl:311
 in macro expansion at .\task.jl:327 [inlined]
 in add(::String, ::Base.Pkg.Types.VersionSet) at .\pkg\entry.jl:51
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at .\pkg\dir.jl:31
 in add(::String) at .\pkg\pkg.jl:100

**Comment by odow** [comment]
To remove `Pkg.rm("CPLEX")`
To add `Pkg.add("CPLEX")`
To checkout my patch `Pkg.checkout("CPLEX", "odow-patch-1")`
To build `Pkg.build("CPLEX")`

**Comment by parsafard** [comment]
Thanks @odow, but I cannot add "CPLEX" anymore. I used Pkg.rm("CPLEX") but it did not update the build.jl. So, I removed CPLEX folders everywhere (e.g. .julia\v0.5.cache and .julia\v0.5.metadata) to reinstall it with new build.jl and ended up with this error.

julia> Pkg.add("CPLEX")
ERROR: unknown package CPLEX
 in macro expansion at .\pkg\entry.jl:53 [inlined]
 in (::Base.Pkg.Entry.##2#5{String,Base.Pkg.Types.VersionSet})() at .\task.jl:360
 in sync_end() at .\task.jl:311
 in macro expansion at .\task.jl:327 [inlined]
 in add(::String, ::Base.Pkg.Types.VersionSet) at .\pkg\entry.jl:51
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at .\pkg\dir.jl:31
 in add(::String) at .\pkg\pkg.jl:100

**Comment by odow** [comment]
Run `Pkg.update()` first, then go through the four steps above.

**Comment by odow** [comment]
Actually since Miles merged, you will just need to run
```
Pkg.update()
Pkg.rm("CPLEX")
Pkg.add("CPLEX")
Pkg.checkout("CPLEX")
Pkg.build("CPLEX")
```

**Comment by parsafard** [comment]
Still it is not working and cannot add CPLEX. Maybe I need to reinstall cplex_studio?

julia> Pkg.add("CPLEX")
ERROR: unknown package CPLEX
...

**Comment by mlubin** [comment]
Your julia package directory is corrupted. Best to delete/rename ``.julia\v0.5`` completely.

**Comment by mlubin** [comment]
You will have to reinstall all current packages.
