### ISSUE TITLE
Error loading parameter CPXPARAM_Benders_Strategy

### ISSUE THREAD

**Issue by davidov77** [JuliaOpt/CPLEX.jl#122]
Hi,

In CPLEX 12.7 they introduced an option for [automatic Benders decomposition](https://www.ibm.com/support/knowledgecenter/en/SSSA5P_12.7.0/ilog.odms.cplex.help/CPLEX/Parameters/topics/BendersStrategy.html)

I have been trying to use it, but I get an error (it seems this option is not included in CplexSolver)
```julia
m= MathProgBase.LinearQuadraticModel(CplexSolver(CPXPARAM_Benders_Strategy=3))
```

I'm starting with Julia, and any help would be greatly appreciated!

Thanks!

**Comment by mlubin** [comment]
Looks like [this dictionary](https://github.com/JuliaOpt/CPLEX.jl/blob/c6036588c893f9661369068a07b28485a6dd411e/src/cpx_params.jl#L148) needs to be updated. It should be split version-wise into ``full_defines_126.jl`` and ``full_defines_127.jl``.

**Comment by mlubin** [comment]
Note the parameter appears as ``CPX_PARAM_BENDERSSTRATEGY``.
