### ISSUE TITLE
Add support for CPLEX v12.7.1.0

### ISSUE THREAD

**Issue by Thuener** [JuliaOpt/CPLEX.jl#123]
I don't think there are big changes from version 12.7.0 to 12.7.1.0. I just added the version "1271" to cpxvers in deps/build.jl, the results from tests in test/runtests.jl seems fine.

**Comment by mlubin** [comment]
It's also a good idea to check that parameters haven't been renumbered, https://github.com/JuliaOpt/CPLEX.jl/blob/master/src/full_defines_127.jl

**Comment by Thuener** [comment]
There are some differences, most of them on the beginning of the file.
[new_full_defines_127.txt](https://github.com/JuliaOpt/CPLEX.jl/files/890679/new_full_defines_127.txt)

**Comment by mlubin** [comment]
I wouldn't expect much to happen here until someone who wants to use 12.7.1 submits a PR.

**Comment by mlubin** [comment]
Closed by #131
