### ISSUE TITLE
I am not able to use cplex solver i have both versions 12.6,12.7 and attached the error mssage. can you help out.

### ISSUE THREAD

**Issue by gpinu1** [JuliaOpt/CPLEX.jl#124]
![image](https://cloud.githubusercontent.com/assets/26877935/24716663/fcb11494-19ec-11e7-96d6-b76307d44464.png)

**Comment by odow** [comment]
Have you read https://github.com/JuliaOpt/CPLEX.jl#note-for-windows and run `Pkg.build("CPLEX")`?
