### ISSUE TITLE
CPLEX V12.7.1 not included

### ISSUE THREAD

**Issue by mckeeta** [JuliaOpt/CPLEX.jl#127]
Version 1271 is not in `deps/build.jl`, only 
```julia
cpxvers = ["1260","1261","1262","1263","1270"]
```
Should I try to download an earlier version?

**Comment by blegat** [comment]
[Normally](http://semver.org/), there should only be backwards-compatible bug fixes between 12.7.0 and 12.7.1 so the wrapper should work with 12.7.1.
Can you check that it is indeed the case, by adding "1271" to the list and run
```julia
Pkg.build("CPLEX")
Pkg.test("CPLEX")
```
