### ISSUE TITLE
include cplex v12.7.1

### ISSUE THREAD

**Issue by abelb0rges** [JuliaOpt/CPLEX.jl#145]
hi. firstly, nice pkg!

readme tells me that I should open an issue if my cplex version is not included on deps/build.jl: here I am. I'm available to help fixing this (I just don't know exactly how).

cheers!

**Comment by odow** [comment]
12.7.1 is included? https://github.com/JuliaOpt/CPLEX.jl/blob/master/deps/build.jl#L20

**Comment by abelb0rges** [comment]
hi. it wasn't included in the version downloaded with Pkg.add("CPLEX"). I cloned this repo and Pkg.build("CPLEX") returns an error:
```
INFO: Building CPLEX
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/abel/.julia/v0.4/CPLEX/deps/build.jl:18
================================[ ERROR: CPLEX ]================================

LoadError: Unable to locate CPLEX installation. Note this must be downloaded separately. See the CPLEX.jl README for further instructions.
while loading /home/abel/.julia/v0.4/CPLEX/deps/build.jl, in expression starting on line 38

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: CPLEX had build errors.

 - packages with build errors remain installed in /home/abel/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("CPLEX")`
 - build a single package by running its `deps/build.jl` script

================================================================================
```
I'm running julia 0.4.5 on an ubuntu 16.04 machine.
I've set `CPLEX_STUDIO_BINARIES` to cplex bin path according to readme.
I removed calls like is_apple() from deps/build.jl because of an error saying that they were not defined.
it looks like my installation of cplex itself has a problem (even though installation process was smooth). for instance, running python examples on the cplex examples folder throws an error on "import cplex" line saying there is no cplex module.
I know this is not related to CPLEX.jl, but any light here? thanks!

**Comment by odow** [comment]
You should upgrade to the latest version of Julia (https://julialang.org/downloads/). CPLEX.jl dropped support for Julia v0.4 in November 2016.

**Comment by abelb0rges** [comment]
It loads just fine now. Thank you!
