### ISSUE TITLE
No support for CPLEX 12.8

### ISSUE THREAD

**Issue by sharabhs** [JuliaOpt/CPLEX.jl#148]
Need to get support for CPLEX 12.8, I am getting a build error for CPLEX 12.8, I assumes this build error is for missing CPLEX 12.8. Will appreciate if somebody can quickly put an update for the same.

**Comment by odow** [comment]
For a quick fix, you could modify the build script [here](https://github.com/JuliaOpt/CPLEX.jl/blob/master/deps/build.jl#L20) and [here](https://github.com/JuliaOpt/CPLEX.jl/blob/master/deps/build.jl#L34) to include 128 and 1280, however I understand Cplex has changed their API, particularly around callbacks, so other functionality might be broken. You should also follow https://github.com/JuliaOpt/CPLEX.jl/issues/123 with respect to the parameters.

 It would be super useful if you had the time to investigate the update and make a PR with any changes that need to be made :)

**Comment by mlubin** [comment]
Closed by https://github.com/JuliaOpt/CPLEX.jl/pull/151. No new API calls have been wrapped yet.
