### ISSUE TITLE
CPLEX 12.8 support

### ISSUE THREAD

**Issue by melihozlen** [JuliaOpt/CPLEX.jl#149]
Hi,
IBM released a new version of CPLEX 12.8. It would be great if that can be supported by the jl package. Thanks.

melih

**Comment by odow** [comment]
Duplicate of https://github.com/JuliaOpt/CPLEX.jl/issues/148.

@melihozlen it would be great if you had the time to follow the advice in the linked issue and investigate if it works / what changes need to be made.
