### ISSUE TITLE
CPLEX.jl not compatible with IBM Ilog CPLEX optimization studio version 128

### ISSUE THREAD

**Issue by dellafailleh** [JuliaOpt/CPLEX.jl#150]
Hello,

I am trying to use this CPLEX.jl package. I am on windows.
Julia returns this while building the package:
"LoadError: Unable to locate CPLEX installation. Note this must be downloaded separately. See the CPLEX.jl README for further instructions.
while loading C:\Users\Harold\.julia\v0.6\CPLEX\deps\build.jl, in expression starting on line 63"

But I have the IBM Ilog CPLEX optimization studio version 128.
Could it be possible that this verion is not compatible with julia yet?

Thanks for the help!

**Comment by odow** [comment]
See #148 and #149
