### ISSUE TITLE
Build Error - Debian

### ISSUE THREAD

**Issue by jnederlo** [JuliaOpt/CPLEX.jl#165]
I'm getting a build error when I try to install CPLEX on Debian 9.3. 

```
INFO: Installing CPLEX v0.3.1
INFO: Building CPLEX
===============================[ ERROR: CPLEX ]===============================
LoadError: Unable to locate CPLEX installation. Note this must be downloaded s
eparately. See the CPLEX.jl README for further instructions.
```

I'm running julia 0.6.2 and I set the LD_LIBRARY_PATH as follows:

```
$ declare -x LD_LIBRARY_PATH="/opt/ibm/ILOG/CPLEX_Studio_Community128/
cplex/bin/x86-64_linux:"
```

Any idea what the issue might be? I was able to install it on my mac no problem.

**Comment by blegat** [comment]
What happens if you do
```
CPLEX_STUDIO_BINARIES="/opt/ibm/ILOG/CPLEX_Studio_Community128/
cplex/bin/x86-64_linux" julia -e 'Pkg.build("CPLEX")'
```

**Comment by odow** [comment]
Dud you follow the instructions in the README? 
https://github.com/JuliaOpt/CPLEX.jl#if-youre-on-linux

Do let us know if we could make the README more helpful.

**Comment by jnederlo** [comment]
I have set the CPLEX_STUDIO_BINARIES Environment Variable from the instructions but I still get the same error, here are the ENV variables:

`"LD_LIBRARY_PATH"  => "/opt/ibm/ILOG/CPLEX_Studio_Community128/cplex/bin/x86-64_linux"`
`"CPLEX_STUDIO_BINARIES" => "/opt/ibm/ILOG/CPLEX_Studio_Community128/cplex/bin/x86-64_linux"`

**Comment by odow** [comment]
A fix for the v12.8 install on Linux hadn't been released yet. Wait for [this PR](https://github.com/JuliaLang/METADATA.jl/pull/13519) to be merged and then run `Pkg.update()`.

If it's urgent, run `Pkg.checkout("CPLEX", "master")` to get the latest version, but remember to run `Pkg.free("CPLEX")` once the PR is merged.

**Comment by odow** [comment]
@jnederlo this should be resolved. Please re-open the issue if it still doesn't work.

**Comment by jnederlo** [comment]
@odow, thanks for your help, I was able to get it with `Pkg.checkout("CPLEX", "master")` but I'll try updating and freeing to get the current version.
