### ISSUE TITLE
Clarify README for windows installs

### ISSUE THREAD

**Issue by cdeterman** [JuliaOpt/CPLEX.jl#168]
I see a few previous issues here regarding the install with CPLEX and I have failed to succeed from any of the results.    

I continue to get the dreaded `Unable to locate CPLEX installation` error.

The issue [here](https://github.com/JuliaOpt/CPLEX.jl/issues/106) seemed optimistic for me but running

```jl
Pkg.update()
Pkg.rm("CPLEX")
Pkg.add("CPLEX")
Pkg.checkout("CPLEX")
Pkg.build("CPLEX")
```

I do have the `CPLEX_STUDIO_BINARIES` environmental variable defined which points to the directory containing 

`CPLEX_Studio127/coptimizer/bin/x64_win64`
* cp_wrap_cpp_dotnet1270.dll
* cp_wrap_cpp_java1270.dll
* cpoptimizer.exe
* ILOC.CP.dll

I also tried the  `CPLEX_Studio127/cplex/bin/x64_win64` directory which contained the follwoing files

- convert
- cplex
- cplex1270.dll
- cplex1270processtransport.dll
- cplex1270processworker.dll
- cplex1270remote.dll
- cplex1270remotejni.dll
- cplex1270tcpiptransport.dll
- cplex1270tcpipworker.dll
- cplexamp
- ILOG.Concert.dll
- ILOG.Concert
- ILOG.CPLEX.dll
- ILOG.CPLEX

 Is there anything else I could be missing here that this build continues to fail?

**Comment by cdeterman** [comment]
I managed to solve it, after looking at the build.jl I noticed that I need the version on the environmental variable.  Setting `CPLEX_STUDIO_BINARIES127` to the `cplex` binary directory solved the problem.

**Comment by odow** [comment]
The readme should be updated to be more helpful.

**Comment by chengg04** [comment]
Don't have CPLEX in my Windows machine:(
