### ISSUE TITLE
Missing CPLEX parameters for CALLBACKCONTEXT

### ISSUE THREAD

**Issue by chengg04** [JuliaOpt/CPLEX.jl#169]
Those parameters are missing in the full_defines_1280.jl file:
```
#define CPX_CALLBACKCONTEXT_CANDIDATE 0x0020
#define CPX_CALLBACKCONTEXT_GLOBAL_PROGRESS 0x0010
#define CPX_CALLBACKCONTEXT_LOCAL_PROGRESS 0x0008
#define CPX_CALLBACKCONTEXT_RELAXATION 0x0040
#define CPX_CALLBACKCONTEXT_THREAD_DOWN 0x0004
#define CPX_CALLBACKCONTEXT_THREAD_UP 0x0002
```
They were missed because their values are long, thus weren't catched by the regular expression used for building it. @odow you may want to update https://github.com/odow/CPLEX.jl/blob/1e7416f1af8a3b229b5ff69508a9589942ee0060/src/cpx_defines/build_defines_file.jl :)
Those are necessary parameters for generic callbacks. So suggest anyone who's going to implement generic callback themselves adding those to the full_defines file. 
Need to open a PR to include those parameters. Maybe when generic callbacks are ready.

**Comment by chengg04** [comment]
@joehuchette Right, they need to be converted to Clong. Just modified them and commited to the PR. Are they correct?

**Comment by joehuchette** [comment]
Looks good to me (not sure why my comment ended up here instead of on the PR). Thanks!
