### ISSUE TITLE
cbgetlpsolution returns assertionerror

### ISSUE THREAD

**Issue by elchiconuevo** [JuliaOpt/CPLEX.jl#171]
I'm trying to collect some info using an `infocallback` illustrated in the callback section of the JuMP document. When I try to access the fractional lp solution at the root node using `cbgetlpsolution` within the infocallback function, I get an assertion error. This is the function I use to add the infocallback to the model. 
`addinfocallback(mdl, infocallback, when = :Intermediate)`

The objective is to access the fractional solution similar to [this](https://www.ibm.com/developerworks/community/forums/html/topic?id=77777777-0000-0000-0000-000014553011&ps=25). How can I achieve this in JuMP?

**Comment by odow** [comment]
Can you provide a complete exmaple that demonstrates the problem? See https://stackoverflow.com/help/mcve

**Comment by elchiconuevo** [comment]
A simple MWE (based on knapsack.jl) of the problem I have. I want to get the fractional LP value of variable x at the root node. However, I get a warning here: `Variable value not defined for component of x. Check that the model was solved properly`

```
using JuMP
using CPLEX

type NodeData
  time::Float64  # in seconds since the epoch
  node::Int
  obj::Float64
  bestbound::Float64
  x_val::Array{Float64,1}
end

m = Model(solver=CplexSolver(CPX_PARAM_NODELIM = 0))

@variable(m, x[1:5], Bin)

profit = [ 5, 3, 2, 7, 4 ]
weight = [ 2, 8, 4, 2, 5 ]
capacity = 10

# Objective: maximize profit
@objective(m, Max, dot(profit, x))

# Constraint: can carry all
@constraint(m, dot(weight, x) <= capacity)

bbdata = NodeData[]

function infocallback(cb)
  node      = MathProgBase.cbgetexplorednodes(cb)
  obj       = MathProgBase.cbgetobj(cb)
  bestbound = MathProgBase.cbgetbestbound(cb)
  x_val = getvalue(x)
  push!(bbdata, NodeData(time(),node,obj,bestbound, x_val))
end
addinfocallback(m, infocallback, when = :Intermediate)

solve(m)
```

**Comment by odow** [comment]
I haven't used the callbacks in CPLEX, however it looks like the solution is only available for `when=:MIPnode` for the `infocallback`. 

https://github.com/JuliaOpt/JuMP.jl/blob/37ab6795eaa269bb762eb11dbba350eb8379bfb1/src/callbacks.jl#L170

You could try `addlazycallback(m, infocallback)` instead.

The new version of JuMP will not support solver independent callbacks. The behaviour is too solver-dependent.

**Comment by elchiconuevo** [comment]
> I haven't used the callbacks in CPLEX, however it looks like the solution is only available for when=:MIPnode for the infocallback

 Is this behaviour independent of the solver? I mean if I switch to another solver, lets say Gurobi, the solution would still not be available?

**Comment by odow** [comment]
Presumably you're trying to follow https://discourse.julialang.org/t/accessing-the-root-node-solution/10371/7?

This is not a CPLEX.jl issue. The infocallback only supports querying the LP solution in the following states 
https://github.com/JuliaOpt/CPLEX.jl/blob/81d7dbb9947960f56c81f7b32dcdf612fa99f7ba/src/CplexSolverInterface.jl#L373-L374

The variable values are not available for `when=:Intermediate`.

I'm not sure what the story with Gurobi is, but according to 
https://github.com/JuliaOpt/JuMP.jl/blob/37ab6795eaa269bb762eb11dbba350eb8379bfb1/src/callbacks.jl#L165-L170
the solution will not be available for `when=:Intermediate`.

**Comment by odow** [comment]
Closing this since it relates to the old JuMP callbacks, which we won't be fixing. The new MOI wrapper implements solver-independent MOI callbacks, and provides access to solver-specific generic CPLEX callbacks.
