### ISSUE TITLE
UndefVarError in a callback wrap

### ISSUE THREAD

**Issue by chengg04** [JuliaOpt/CPLEX.jl#176]
When writing the wrap for a callback function in CPLEX 12.80, I encountered an error `UndefVarError: void not defined`. It's strange since there is no variable called `void` anywhere in the code. Can anyone help me to find out where the bug is?

To reproduce, use codes from here:  https://github.com/chengg04/CPLEX.jl/blob/cheng_test/src/cpx_newcbs.jl and here: https://github.com/chengg04/CPLEX.jl/blob/cheng_test/examples/admipex9_cb.jl and build the model with sentoy.mps from CPLEX 12.80 folder /Applications/CPLEX_Studio128/cplex/examples/data/ (default path in MacOS)

The example is based on /Applications/CPLEX_Studio128/cplex/examples/src/c/admipex9.c 

Another issue (unrelated to the one above) is when optimizing the model without callback, I got the optimal objective as 0, which is wrong. Might be caused by a minor bug but I'm unable to locate it.

**Comment by odow** [comment]
You need to use `Void` instead of `void` here:
https://github.com/chengg04/CPLEX.jl/blob/23fa065eab0d7686f329607b87cc547118b362cf/src/cpx_newcbs.jl#L76

**Comment by chengg04** [comment]
Indeed. Thank you so much!
