### ISSUE TITLE
Errors when installing CPLEX on Julia 1.0

### ISSUE THREAD

**Issue by nhavt** [JuliaOpt/CPLEX.jl#182]
Hi all, when installing CPLEX, I obtained an error ( see at
[CPLEX_error.txt](https://github.com/JuliaOpt/CPLEX.jl/files/2331727/CPLEX_error.txt)). Could someone please have a look at it? My guess is that the current version of CPLEX is not compatible with Julia 1.0. So, is it possible to run CPLEX on Julia 1.0 at the moment? Thanks in advance!

**Comment by IssamT** [comment]
Hi. You are right. It's not compatible yet.

**Comment by nhavt** [comment]
Hi @IssamT, thanks for your response. So, could you please tell me when I can use the CPLEX on Julia 1.0? Thanks in advance!

**Comment by IssamT** [comment]
I am afraid I can't answer your question, especially if you are trying to use it with JuMP.

**Comment by mlubin** [comment]
Closed by https://github.com/JuliaOpt/CPLEX.jl/pull/184
