### ISSUE TITLE
Unable to build package CPLEX

### ISSUE THREAD

**Issue by ZacharieALES** [JuliaOpt/CPLEX.jl#187]
Hello,

I am using CPLEX 1271 and julia-1.0.1 on windows 10. When I try to build CPLEX I get the following error:
```
julia> Pkg.build("CPLEX")
  Building CPLEX → `C:\Users\billy\.julia\packages\CPLEX\FUtHu\deps\build.log`
┌ Error: Error building `CPLEX`:
│ ERROR: LoadError: UndefVarError: is_apple not defined
│ Stacktrace:
│  [1] top-level scope at none:0
│  [2] include at .\boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at .\loading.jl:1041
│  [4] include(::Module, ::String) at .\sysimg.jl:29
│  [5] include(::String) at .\client.jl:388
│  [6] top-level scope at none:0
│ in expression starting at C:\Users\billy\.julia\packages\CPLEX\FUtHu\deps\build.jl:18
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1069
```

I tried to set the variable CPLEX_STUDIO_BINARIES but it did not help:
`julia> ENV["CPLEX_STUDIO_BINARIES"] = "C:\\Users\\billy\\Documents\\IBM\\ILOG\\CPLEX_Studio1271" `

Do you have any idea how I could solve this problem?

**Comment by ZacharieALES** [comment]
Ok. Thanks for your quick answer. If I want to use CPLEX, I should try julia previous version? (julia 0.7.0?)

**Comment by IssamT** [comment]
Julia 0.6

**Comment by mlubin** [comment]
Closed by https://github.com/JuliaOpt/CPLEX.jl/pull/184
