### ISSUE TITLE
Inspect multiple solutions

### ISSUE THREAD

**Issue by stelmo** [JuliaOpt/CPLEX.jl#189]
Hi,

I am busy writing a program that needs to explore the solution space of an LP with multiple optima. Based on [this](https://www-01.ibm.com/support/docview.wss?uid=swg21399929) post it seems that this can be done using most of the already wrapped functions. However, an iteration limit parameter needs to be passed to the Cplex solver. Is this already implemented somewhere? I looked but couldn't find it. If not, who should I beg to please add it (I looked at your source code to see if I can add it myself, but it looked a bit daunting...)?

**Comment by odow** [comment]
See https://github.com/JuliaOpt/CPLEX.jl#parameters

For example, if you want to set
https://github.com/JuliaOpt/CPLEX.jl/blob/9e60e3db5175917e32c50b27b59854aaf50320bd/src/cpx_params_1280.jl#L345

```julia
solver = CPLEX.CplexSolver(CPXPARAM_Simplex_Limits_Iteration = 10)
```

**Comment by stelmo** [comment]
Thank you very much! It is working!
