### ISSUE TITLE
error building Cplex in Julia 1.0

### ISSUE THREAD

**Issue by husseintarhini** [JuliaOpt/CPLEX.jl#190]
while building CPLEX, i get the following message:

┌ Error: Error building `CPLEX`:
│ ERROR: LoadError: UndefVarError: contains not defined
│ Stacktrace:
│  [1] top-level scope at C:\Users\husse\AppData\Local\JuliaPro-1.0.1.1\pkgs-1.0.1.1\packages\CPLEX\
0dScx\deps\build.jl:44
│  [2] include at .\boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at .\loading.jl:1041
│  [4] include(::Module, ::String) at .\sysimg.jl:29
│  [5] include(::String) at .\client.jl:388
│  [6] top-level scope at none:0
│ in expression starting at C:\Users\husse\AppData\Local\JuliaPro-1.0.1.1\pkgs-1.0.1.1\packages\CPLE
X\0dScx\deps\build.jl:39
└ @ Pkg.Operations C:\Users\julia\AppData\Local\Julia-1.0.1\share\julia\stdlib\v1.0\Pkg\src\Operatio
ns.jl:1101

**Comment by husseintarhini** [comment]
Can you please elaborate on this?

**Comment by mlubin** [comment]
The build script is broken on Windows on Julia 1.0 and needs to be fixed:

https://github.com/JuliaOpt/CPLEX.jl/blob/9e60e3db5175917e32c50b27b59854aaf50320bd/deps/build.jl#L44

**Comment by blegat** [comment]
It should be fixed on master but I don't have a Windows machine to test it.
@husseintarhini Could you give us the output of:
```julia
] add CPLEX#master
] build CPLEX
```

**Comment by husseintarhini** [comment]
It worked, thanks!
