### ISSUE TITLE
Not really an issue, delete a constraint that genereate conflict

### ISSUE THREAD

**Issue by giadasp** [JuliaOpt/CPLEX.jl#200]
I'm sorry to open an issue but I didn't find a blog in which I can ask the following question, please close this issue as soon as you prefer.

I would like to delete a constraint from an infeasible model, in particular when I run `solve(m)` I have an infeasibility generated by, let's say, constraint 'c2000', how can I delete this constraint using this CPLEX internal index?

Thank you  for your attention.
Giada

**Comment by odow** [comment]
The current version of JuMP is unable to delete constraints from a model. 

However, the upcoming release will support this. Please see: https://discourse.julialang.org/t/mathoptinterface-and-upcoming-breaking-changes-in-jump-0-19/4874
