### ISSUE TITLE
CPLEX with indefinite quadratic objective

### ISSUE THREAD

**Issue by stumarcus576** [JuliaOpt/CPLEX.jl#205]
I am trying to use CPLEX 12.7.1 to solve a MIQP in JuMP with Julia 0.6.4, but get an error (shown below) complaining that the quadratic term in not positive definite. This CPLEX link says that CPLEX 12.7.1 should be able to solve indefinite quadratic MIQP to global optimality: https://www.ibm.com/support/knowledgecenter/SSSA5P_12.6.3/ilog.odms.studio.help/CPLEX/ReleaseNotes/topics/releasenotes126/newNonconvexMIQP.html

I set the solver and objective in JuMP via:
const solver = CplexSolver(CPX_PARAM_THREADS=0,CPX_PARAM_TILIM=tl,CPX_PARAM_EPAGAP=optca,CPX_PARAM_EPGAP=optcr,CPX_PARAM_OPTIMALITYTARGET=3)

@variable(m,min_dim[d] <= x[d=1:3] <= r_max_dim[d])
x0 = [28.0, 26.0, 6.0]+[1,1,1]
@variable(m,lower_volume<=volume<=upper_volume)
@constraint(m,volume == x0[1]*x0[2]*x0[3]+(x[1]-x0[1])*x0[2]*x0[3]+x0[1]*(x[2]-x0[2])*x0[3]+x0[1]*x0[2]*(x[3]-x0[3])+(x[1]-x0[1])*(x[2]-x0[2])*x0[3]+(x[1]-x0[1])*x0[2]*(x[3]-x0[3])+x0[1]*(x[2]-x0[2])*(x[3]-x0[3])) 
@objective(m,Min,volume)

ERROR: LoadError: CPLEX.CplexError(5002, "CPLEX Error  5002: Q in '%s' is not positive semi-definite.\n")
Stacktrace:
 [1] optimize!(::CPLEX.Model) at /Users/a598124/.julia/v0.6/CPLEX/src/cpx_solve.jl:23
 [2] optimize!(::CPLEX.CplexMathProgModel) at /Users/a598124/.julia/v0.6/CPLEX/src/CplexSolverInterface.jl:192
 [3] #solve#133(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model) at /Users/a598124/.julia/v0.6/JuMP/src/solvers.jl:175
 [4] solve(::JuMP.Model) at /Users/a598124/.julia/v0.6/JuMP/src/solvers.jl:150
 [5] include_from_node1(::String) at ./loading.jl:576
 [6] include(::String) at ./sysimg.jl:14
 [7] process_options(::Base.JLOptions) at ./client.jl:305
 [8] _start() at ./client.jl:371
while loading /Users/a598124/juliaCode/boxPacking5/MVB_MIQP.jl, in expression starting on line 237

**Comment by stumarcus576** [comment]
If I set the objective directly as shown below, then CPLEX works properly. Is there a way to place bounds on the objective, without creating a bounded variable and constraint, like I did in the initial post?

@objective(m,Min,x0[1]*x0[2]*x0[3]+(x[1]-x0[1])*x0[2]*x0[3]+x0[1]*(x[2]-x0[2])*x0[3]+x0[1]*x0[2]*(x[3]-x0[3])+(x[1]-x0[1])*(x[2]-x0[2])*x0[3]+(x[1]-x0[1])*x0[2]*(x[3]-x0[3])+x0[1]*(x[2]-x0[2])*(x[3]-x0[3]))

**Comment by odow** [comment]
Hi @stumarcus576 

From the docs you linked to
> CPLEX V12.6.0 is capable of solving a quadratic program (that is, a problem with linear constraints and one or more quadratic terms in the objective function) for which the space of optimal solutions is not convex to global optimality.

This implies that you can't have quadratic constraints. This explains why your first problem failed, but the second one succeeded. I don't know of any way to constraint the objective without doing what you suggest. It's just a hard problem to solve! Do you really need the bounds?

p.s. In future, please use the Discourse forum (https://discourse.julialang.org/c/domain/opt) for questions like this. We try to reserve Github issues for bug reports.

**Comment by stumarcus576** [comment]
The bounds are not necessary, but I thought the bounds might help the solver find a solution faster.

**Comment by odow** [comment]
Just solve it without the bounds. Also, if you can find a heuristic solution you can provide it as a starting solution with `@variable(model, x, start = 1)`.

I'm going to close this issue since everything is working as expected.
