### ISSUE TITLE
[Mac OS] No output from CPLEX after running optimize!(mymodel)

### ISSUE THREAD

**Issue by haokuny** [JuliaOpt/CPLEX.jl#216]
The following simple example has been tested but no output is returned.
```julia
julia> using JuMP, CPLEX
julia> mymodel = Model(with_optimizer(CPLEX.Optimizer))
julia> @variable(mymodel, 0 <= x <=2)
julia> @objective(mymodel, Max, x)
julia> optimize!(mymodel)
```
I am sure the model is been properly solved because I can get solution by calling `JuMP.value.(x)`, or `objective_value(mymodel)`.
I tried the same thing on my windows 10 machine and it returned the solving statement correctly.
I tried using another solver GUROBI, `optimize(mymodel, with_optimizer(Gurobi.Optimizer))` and it did returned the solving statement from GUROBI, so I guess there might be something wrong with CPLEX.jl on Mac OS (macOS High Sierra Version 10.13.6 in my case).
I also tried `Pkg.update()` and rebuilt CPLEX by `Pkg.build(CPLEX)` but the issue (no output) still exists.

**Comment by mikeKAH** [comment]
I experience the same (after updating to JuMP 0.19) which required me to  to change the command of creating a model to

`model = Model(with_optimizer(CPLEX.Optimizer, CPX_PARAM_MIPDISPLAY = 2 ))`.

So, even if I force a screen output like that nothing is printed. Notice that I use Ubuntu 18.04, Julia 1.1, JuMP 0.19, MathOptInterface v0.8.2, CPLEX v0.4.3 to start CPLEX 12.8.

**Comment by haokuny** [comment]
> I experience the same (after updating to JuMP 0.19) which required me to to change the command of creating a model to
> 
> `model = Model(with_optimizer(CPLEX.Optimizer, CPX_PARAM_MIPDISPLAY = 2 ))`.
> 
> So, even if I force a screen output like that nothing is printed. Notice that I use Ubuntu 18.04, Julia 1.1, JuMP 0.19, MathOptInterface v0.8.2, CPLEX v0.4.3 to start CPLEX 12.8.

Yes, this issue happened exactly after I updated JuMP to version 0.19.

**Comment by odow** [comment]
What happens if you set `CPX_PARAM_SCRIND=1`?
It looks like we used to turn this on by default:
https://github.com/JuliaOpt/CPLEX.jl/blob/13d849b4ae3e34b276b4160f0cffe4954faac6cb/src/CplexSolverInterface.jl#L21

Not any more:
https://github.com/JuliaOpt/CPLEX.jl/blob/13d849b4ae3e34b276b4160f0cffe4954faac6cb/src/MOI_wrapper.jl#L44-L52

**Comment by odow** [comment]
There is a bug: even if we pass in an existing environment, we create a new one...
https://github.com/JuliaOpt/CPLEX.jl/blob/a09be2e0fabc38dfaec75f67b9039a70d2b0c1e7/src/MOIWrapper.jl#L39-L42

**Comment by mikeKAH** [comment]
> What happens if you set `CPX_PARAM_SCRIND=1`?


Nothing happens. It is the same behaviour as before.

**Comment by odow** [comment]
See #218

**Comment by haokuny** [comment]
@odow Thanks very much for the help! I assume that you have figured out the problem so you could get an output form CPLEX in your local machine. Is that right? If so, I would close this issue and wait for your pull request #218 .
