### ISSUE TITLE
Quadratic in MOI

### ISSUE THREAD

**Issue by odow** [JuliaOpt/CPLEX.jl#217]
As reported in Discourse: https://discourse.julialang.org/t/quadratic-programming-problem-cpl/21068/3

The CPLEX wrapper hasn't implemented the quadratic components yet. Pull requests accepted :)

It shouldn't be too hard because you can copy the Gurobi implementation (it's more or less just matching up the different C names).

You would need to edit the [`CPLEX/src/MOI_wrapper.jl`](https://github.com/JuliaOpt/CPLEX.jl/blob/master/src/MOI_wrapper.jl) and add the functions beginning with `LQOI.` and containing `quadratic` in the Gurobi wrapper:
https://github.com/JuliaOpt/Gurobi.jl/blob/f1418b5c470fb91b417e3424241a3440078c9212/src/MOI_wrapper.jl#L311-L367

You also have to add these lines to the list of supported objectives
https://github.com/JuliaOpt/Gurobi.jl/blob/f1418b5c470fb91b417e3424241a3440078c9212/src/MOI_wrapper.jl#L9
and constrints
https://github.com/JuliaOpt/Gurobi.jl/blob/f1418b5c470fb91b417e3424241a3440078c9212/src/MOI_wrapper.jl#L17-L19

**Comment by trigaut** [comment]
Can we close this one @odow ?

**Comment by odow** [comment]
Closed by #231
