### ISSUE TITLE
How to add callbacks?

### ISSUE THREAD

**Issue by mikeKAH** [JuliaOpt/CPLEX.jl#222]
Hi,
I am a bit puzzled on who is "responsible" for my question, hence, I opened a thread also [here](https://discourse.julialang.org/t/adding-cplex-callbacks-with-jump-v0-19/21449). In a nutshell, I updated to JuMP v0.19, and it's documentation says that callbacks are now solver-specific. However, I do not find something about adding callbacks here in the documentation nor in the MathOptInterface docs. 
So my question is, what is the right way to add callbacks?
Thank you in advance.

**Comment by odow** [comment]
Per [my reply on Discourse](https://discourse.julialang.org/t/adding-cplex-callbacks-with-jump-v0-19/21449/8?u=odow), there is unlikely to be any movement before we come to a consensus.

Here is one proposal with the plumbing from JuMP -> MOI -> Gurobi.

JuMP: https://github.com/JuliaOpt/JuMP.jl/pull/1849
MOI: https://github.com/JuliaOpt/MathOptInterface.jl/pull/670
Gurobi: https://github.com/JuliaOpt/Gurobi.jl/pull/194

As @mlubin said, if you require callbacks, use JuMP 0.18 for now.

If you have any ideas about how CPLEX-specific callbacks should look (and you have time), feel free to mock up some demos so we can discuss.

**Comment by mikeKAH** [comment]
Okay, thank you for your reply. In that case I will use JuMP 0.18 until there is a solution. However, I think it is better not to suggest something about CPLEX-specific callbacks since I am more a user than a developer ;).
