### ISSUE TITLE
Version support for CPLEX 12.9

### ISSUE THREAD

**Issue by ChangminWu** [JuliaOpt/CPLEX.jl#227]
According to dep/builds.jl, the current version of this module does not support CPLEX 12.9

**Comment by odow** [comment]
See https://github.com/JuliaOpt/CPLEX.jl/pull/226

**Comment by jd-lara** [comment]
https://github.com/JuliaOpt/CPLEX.jl/pull/226 is now passing tests. Just waiting for approval.
