### ISSUE TITLE
Still unable to locate CPLEX installation with Julia 1.1, after following readme

### ISSUE THREAD

**Issue by edxu96** [JuliaOpt/CPLEX.jl#236]
I still can't install the CPLEX correctly with Julia 1.1. I have checked all the possible problems.

```
$ echo $LD_LIBRARY_PATH
/Users/edxu96/Applications/CPLEX_Studio129/cplex/bin/x86-64_osx/
```

```
$ echo $CPLEX_STUDIO_BINARIES
/Users/edxu96/Applications/CPLEX_Studio129/cplex/bin/x86-64_osx/
```

```julia
julia> ENV["LD_LIBRARY_PATH"]
"/Users/edxu96/Applications/CPLEX_Studio129/cplex/bin/x86-64_osx/"
```

```julia
julia> ENV["CPLEX_STUDIO_BINARIES"]
"/Users/edxu96/Applications/CPLEX_Studio129/cplex/bin/x86-64_osx/"
```

```julia
(v1.1) pkg> build CPLEX
  Building CPLEX → `~/.julia/packages/CPLEX/NzxB3/deps/build.log`
┌ Error: Error building `CPLEX`: 
│ ERROR: LoadError: Unable to locate CPLEX installation. Note this must be downloaded separately. See the CPLEX.jl README for further instructions.
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /Users/edxu96/.julia/packages/CPLEX/NzxB3/deps/build.jl:67
│  [3] include at ./boot.jl:326 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1038
│  [5] include(::Module, ::String) at ./sysimg.jl:29
│  [6] include(::String) at ./client.jl:403
│  [7] top-level scope at none:0
│ in expression starting at /Users/edxu96/.julia/packages/CPLEX/NzxB3/deps/build.jl:66
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075
```

**Comment by odow** [comment]
What files are in the `/Users/edxu96/Applications/CPLEX_Studio129/cplex/bin/x86-64_osx/` directory?

**Comment by edxu96** [comment]
```
cplex
cplexamp
libcplex1290.dylib
libcplex1290.jnilib
libcplex1290mpitransport.dylib
libcplex1290mpiworker.dylib
libcplex1290processtransport.dylib
libcplex1290processworker.dylib
libcplex1290remote.dylib
libcplex1290remotejni.jnilib
libcplex1290tcpiptransport.dylib
libcplex1290tcpipworker.dylib
```

**Comment by remi-garcia** [comment]
Same issue here. I had CPLEX working, then I tried `] build CPLEX`.
`Building CPLEX → `~/.julia/packages/CPLEX/mo9kV/deps/build.log`
┌ Error: Error building `CPLEX`: 
│ ERROR: LoadError: Unable to locate CPLEX installation. Note this must be downloaded separately. See the CPLEX.jl README for further instructions.
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /home/remi/.julia/packages/CPLEX/mo9kV/deps/build.jl:69
│  [3] include at ./boot.jl:326 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1038
│  [5] include(::Module, ::String) at ./sysimg.jl:29
│  [6] include(::String) at ./client.jl:403
│  [7] top-level scope at none:0
│ in expression starting at /home/remi/.julia/packages/CPLEX/mo9kV/deps/build.jl:68
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075`

**Comment by remi-garcia** [comment]
I've no clue why but 2 variables (`LD_LIBRARY_PATH` and `CPLEX_STUDIO_BINARIES`) were not set and it worked anyway. I made the correction and the variable `LD_LIBRARY_PATH` is sufficient.
@edxu96 I don't get the same result as you:
```Julia
julia> ENV["LD_LIBRARY_PATH"]
"/opt/ibm/ILOG/CPLEX_Studio128/cplex/bin/x86-64_linux:"
```
and
```
$ echo $LD_LIBRARY_PATH 
/opt/ibm/ILOG/CPLEX_Studio128/cplex/bin/x86-64_linux:
```
This is my export:
```export LD_LIBRARY_PATH="/opt/ibm/ILOG/CPLEX_Studio128/cplex/bin/x86-64_linux":$LD_LIBRARY_PATH```

**Comment by edxu96** [comment]
I figured it out by doing:
```Julia
julia>using Libdl

julia>push!(DL_LOAD_PATH, "/Applications/CPLEX_Studio129/cplex/bin/x86-64_osx")
3-element Array{String,1}:
 "@loader_path/julia"                                
 "@loader_path"                                      
 "/Applications/CPLEX_Studio129/cplex/bin/x86-64_osx"
```

I don't know why it works.

**Comment by remi-garcia** [comment]
I think the difference is that ```".../bin/x86-64_osx"``` has not the last / while your ```echo``` differ with mine. Can you try an export of ```LD_LIBRARY_PATH``` with no end / to check if you can build this way?

**Comment by edxu96** [comment]
I tried in your way right away after I saw your reply, but it didn't work. I just got this problem solved with teachers' help by using "Libdl".

**Comment by ahmadreza-marandi** [comment]
I have also got the same error on Windows and Julia 1.0.3. Even though the "cplex1290.dll" exists in the path, it can't find it. 
When I checked, I also found that the problem is with the  "Libdl.dlopen_e," which returns NULL. 

I have tried the solutions mentioned above and none of them worked.

**Comment by odow** [comment]
@ahmadreza-marandi please read https://github.com/JuliaOpt/CPLEX.jl#note-for-windows

You need to set `CPLEX_STUDIO_BINARIES129`.

**Comment by ahmadreza-marandi** [comment]
> @ahmadreza-marandi please read https://github.com/JuliaOpt/CPLEX.jl#note-for-windows
> 
> You need to set `CPLEX_STUDIO_BINARIES129`.

@odow I did all the steps, and got the error:

ENV["CPLEX_STUDIO_BINARIES1290"]` ="C:/Program Files/IBM/ILOG/CPLEX_Studio129/cplex/bin/x64_win64";

(v1.0) pkg> build CPLEX
  Building CPLEX → `C:\Users\VM(CPU4 RAM40)\.julia\packages\CPLEX\NzxB3\deps\build.log`
┌ Error: Error building `CPLEX`:
│ ERROR: LoadError: Unable to locate CPLEX installation. Note this must be downloaded separately. See the CPLEX.jl README for further instructions.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] top-level scope at C:\Users\VM(CPU4 RAM40)\.julia\packages\CPLEX\NzxB3\deps\build.jl:67
│  [3] include at .\boot.jl:317 [inlined]
│  [4] include_relative(::Module, ::String) at .\loading.jl:1044
│  [5] include(::Module, ::String) at .\sysimg.jl:29
│  [6] include(::String) at .\client.jl:392
│  [7] top-level scope at none:0
│ in expression starting at C:\Users\VM(CPU4 RAM40)\.julia\packages\CPLEX\NzxB3\deps\build.jl:66
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1097

**Comment by odow** [comment]
What is the output of `] st CPLEX`?

Is there a file `"C:/Program Files/IBM/ILOG/CPLEX_Studio129/cplex/bin/x64_win64/cplex1290.dll"`?

**Comment by ahmadreza-marandi** [comment]
Here is the response I got: 
```
(v1.0) pkg> st CPLEX
ERROR: Wrong number of arguments
```
Indeed, there is the file "cplex1290.dll" but I don't know why it can't recognize it.

**Comment by remi-garcia** [comment]
> `ENV["CPLEX_STUDIO_BINARIES1290"] ="C:/Program Files/IBM/ILOG/CPLEX_Studio129/cplex/bin/x64_win64";`
Shouldn't it be `ENV["CPLEX_STUDIO_BINARIES129"]`? Haven't tried CPLEX on Windows so I can't check.

**Comment by ahmadreza-marandi** [comment]
I have tried both, but none of them works!

**Comment by odow** [comment]
@ahmadreza-marandi what is the output of the following
```Julia
import Pkg
Pkg.update()
Pkg.build("CPLEX")
Pkg.status()

using Libdl
const file = "C:/Program Files/IBM/ILOG/CPLEX_Studio129/cplex/bin/x64_win64/cplex1290.dll"
@show ENV["CPLEX_STUDIO_BINARIES129"]
@show isfile(file)
@show Libdl.dlopen_e(file)
```

**Comment by ahmadreza-marandi** [comment]
@odow: I changed the version to 0.4.4 and worked with the cplex12.7.1. I can give you the output after my code is terminated.

**Comment by ahmadreza-marandi** [comment]
@odow: It seems the problem is resolved.
