### ISSUE TITLE
Unhelpful error message when CPLEX_STUDIO_BINARIES is not an environment variable on windows

### ISSUE THREAD

**Issue by joseortiz3** [JuliaOpt/CPLEX.jl#267]
The installation requires that `CPLEX_STUDIO_BINARIES` be defined, but currently default installation of CPLEX (at least on windows) only sets an environment variable like `CPLEX_STUDIO_BINARIES129`, where 129 is the version number. 

On my windows machine, this resulted in a bizarre `is_apple is not defined` error message upon `Pkg.add("CPLEX")`. Copying the value of `CPLEX_STUDIO_BINARIES129` into a new environment variable `CPLEX_STUDIO_BINARIES` solved this installation problem, despite the error message implying something completely different.

Consider a revision of the installation to check that the correct environment variable has been set, something like "CPLEX_STUDIO_BINARIES129 was found as an environment variable, but installation requires CPLEX_STUDIO_BINARIES instead. Please add this environment variable before proceeding", or some other way of handling this case.

Edit: Here are the versions.
```
julia> Pkg.status("CPLEX")
    Status `C:\Users\Joey\.juliapro\JuliaPro_v1.2.0-1\environments\v1.2\Project.toml`
  [a076750e] CPLEX v0.3.3

julia> Pkg.status("JuMP")
    Status `C:\Users\Joey\.juliapro\JuliaPro_v1.2.0-1\environments\v1.2\Project.toml`
  [4076af6c] JuMP v0.20.0
```
Edit 2: This might be just from using an older version of `CPLEX.jl`.

**Comment by blegat** [comment]
What is the version of CPLEX.jl that you used whan you got the error `is_apple is not defined` ?

**Comment by joseortiz3** [comment]
@blegat Here are the relevant versions.
```
julia> Pkg.status("JuMP")
    Status `C:\Users\Joey\.juliapro\JuliaPro_v1.2.0-1\environments\v1.2\Project.toml`
  [4076af6c] JuMP v0.20.0
```

**Comment by odow** [comment]
What version of CPLEX.jl? i.e., `Pkg.status("CPLEX")`. 

It's likely an issue with JuliaPro packaging an old version of CPLEX.jl that doesn't support v1.2. You need CPLEX.jl v0.6.0.

**Comment by joseortiz3** [comment]
@odow, Oh, I'm so dumb lol. Here you go.
```
julia> Pkg.status("CPLEX")
    Status `C:\Users\Joey\.juliapro\JuliaPro_v1.2.0-1\environments\v1.2\Project.toml`
  [a076750e] CPLEX v0.3.3
```

**Comment by odow** [comment]
I'm not sure with JuliaPro. You likely need to add the "General registry" to add packages that are not bundled with JuliaPro, but I'm not sure how to do this. I'd try Googling or searching the forum https://discourse.julialang.org. 

If all else fails, try
```Julia
Julia> ] add https://github.com/JuliaOpt/CPLEX.jl
```

**Comment by joseortiz3** [comment]
Oh I got it. 
`julia> Pkg.add(PackageSpec(url="https://github.com/JuliaOpt/CPLEX.jl.git"))`
