### ISSUE TITLE
Passing user data in generic callbacks

### ISSUE THREAD

**Issue by mtanneau** [JuliaOpt/CPLEX.jl#282]
In the [CPLEX C api](https://www.ibm.com/support/knowledgecenter/SSSA5P_12.9.0/ilog.odms.cplex.help/refcallablelibrary/typedefs/CPXCALLBACKFUNC.html), a generic callback function has the signature
```C
my_callback_function(CPXCALLBACKCONTEXTptr context,  CPXLONG contextid, void * userhandle)
```
where `context` allows to query/submit information from/to the CPLEX model, `contextid` indicates where the callback is invoked from, and `userhandle` points to a user-specified data structure.

I might have missed something, but it looks like, in the Julia wrapper (see [src/cpx_generic_callbacks.jl](https://github.com/JuliaOpt/CPLEX.jl/blob/master/src/cpx_generic_callbacks.jl)), once cannot pass a user-defined data structure to a generic callback function.

Specifically, the current docs mention
> cpx_callbacksetfunc(model::Model, context_mask::Clong, callback_func::Function)
>
> Set the general callback function of model to `callback_func`.
> 
> `callback_func` is a function that takes two arguments. The first is a
`CallbackContext` instance, and the second is a `Clong` indicating where the
callback is being called from.

Given that
```julia
mutable struct CallbackContext
    model::Model
    context::Ptr{Cvoid}
end
```
where `model` is just the `CPLEX.Model` and `context` corresponds to the `CPXCALLBACKCONTEXTptr` above, it's not clear to me how I can pass some custom data to `callback_func`.

Was this an intended restriction?

cc @chengg04

**Comment by odow** [comment]
Data can be passed using a standard Julia closure:
https://github.com/JuliaOpt/CPLEX.jl/blob/e3ad62c948952af4837a9ac239e50c5e29ad1ee9/test/MathOptInterface/MOI_callbacks.jl#L57-L59

We use the `user_handle` to pass the model and Julia callback function to C: 
https://github.com/JuliaOpt/CPLEX.jl/blob/e3ad62c948952af4837a9ac239e50c5e29ad1ee9/src/cpx_generic_callbacks.jl#L47-L54

**Comment by mtanneau** [comment]
> We use the `user_handle` to pass the model and Julia callback function to C

Would there be any reason against having
```julia

function callback_wrapper(
    context::Ptr{Cvoid}, context_id::Clong, user_handle::Ptr{Cvoid}
)
    (model, callback_func, userdata) = unsafe_pointer_to_objref(user_handle)::Tuple{Model, Function, Any}
    # Run the `callback_func`.
    callback_func(CallbackContext(model, context), context_id, userdata)
    # Exit normally.
    return Cint(0)
end

function cbsetfunc(model::Model, context_mask::Clong, callback_func::Function, userdata)
    ...
    user_handle = (model, callback_func, userdata)::Tuple{Model, Function, Any}
    # rest of the function unchanged
```

Which would make the following work
```julia
import CPLEX

# Counter to be incremented each time the callback is invoked
mutable struct MyCallbackData
    n::Int
end

# Julia-level callback function
function my_callback(context::CPLEX.CallbackContext, contextid::Clong, userdata::MyCallbackData)
    userdata.n += 1
    return Cint(0)
end

env = CPLEX.Env()
cpx_model =  CPLEX.Model(env)

CPLEX.add_var!(cpx_model, 1.0, 0.0, 1.0)
CPLEX.set_vartype!(cpx_model, ['I'])

CBDATA = MyCallbackData(0)
CBWHERE = (2 | 4 | 8 | 16 | 32 | 64)  # Invoke callback in all contexts

CPLEX.cbsetfunc(cpx_model, CBWHERE, my_callback, CBDATA)

CPLEX.optimize!(cpx_model)

println("Callback was invoked $(CBDATA.n) times.")

**Comment by odow** [comment]
> Would there be any reason against having

Yes. Because you can already do the following:

```Julia
import CPLEX
env = CPLEX.Env()
cpx_model =  CPLEX.Model(env)
CPLEX.add_var!(cpx_model, 1.0, 0.0, 1.0)
CPLEX.set_vartype!(cpx_model, ['I'])
CBDATA = MyCallbackData(0)
CBWHERE = (2 | 4 | 8 | 16 | 32 | 64)
function my_callback(context::CPLEX.CallbackContext, contextid::Clong)
    CBDATA.n += 1  # << Just reference the outer variable directly.
    return Cint(0)
end
CPLEX.cbsetfunc(cpx_model, CBWHERE, my_callback)
CPLEX.optimize!(cpx_model)
println("Callback was invoked $(CBDATA.n) times.")
```

**Comment by mlubin** [comment]
Agreed, just use a closure. There's no need to imitate the C API here. The `void*` is workaround for C not having closures.

**Comment by odow** [comment]
Closing since we won't be changing this.
