### ISSUE TITLE
`has_duals` answers differently if variables were originally integers

### ISSUE THREAD

**Issue by henriquebecker91** [JuliaOpt/CPLEX.jl#290]
@odow suggested that I opened a PR here after my [post in Discourse](https://discourse.julialang.org/t/cplex-model-answer-has-duals-differently-if-variables-were-integer/36276). Basically:

```julia
using JuMP
import CPLEX

function test_duals(solver_sym, relaxed_mip)
    solver_lib = getfield(Main, solver_sym)
    m = direct_model(solver_lib.Optimizer())
    set_silent(m)
    if relaxed_mip
        @variable(m, x[1:10] >= 0, Int)
    else
        @variable(m, x[1:10] >= 0)
    end
    @objective(m, Min, sum(x))
    relaxed_mip && unset_integer.(x)
    optimize!(m)
    @show solver_sym
    @show relaxed_mip
    @show has_duals(m)
end

test_duals(:CPLEX, false)
test_duals(:CPLEX, true)
```

Gives `true` for the first case and `false` for the second case, in other words, if the model was a MIP before becoming an LP then the duals do not become available at the end of the LP optimization (both GLPK and Gurobi return `true` in both cases, not just the first). It seems this is not expected behavior but instead it is #110 re-surfacing. I will give it a look, but do not guarantee it will be soon. I need CPLEX working in this case but not now (for now I can just use Gurobi).

**Comment by odow** [comment]
I know how to fix this. I'll make a PR.
