### ISSUE TITLE
Supporting CPLEX version 12.10

### ISSUE THREAD

**Issue by mkhraijah** [JuliaOpt/CPLEX.jl#293]
Hi, 

Thanks in advance for your efforts and support. I would like to file an issue regarding supporting CPLEX version 12.10. As I noticed the CPLEX version supported by JuMP are 12.8 and 12.9, and I want to ask if there is a way to install 12.10 version interface with the current settings. 

Thanks again, 
Mohannad

**Comment by odow** [comment]
Closing as duplicate of #270.
