### ISSUE TITLE
Any MINLP examples?

### ISSUE THREAD

**Issue by MathematicianVogt** [JuliaOpt/CPLEX.jl#303]
Hey, I was curious if it was possible to have more general objective/constraints i.e they are not necessarily linear or quadratic - it seems to me all your examples fall into one of these categories.

Thanks a lot.

**Comment by odow** [comment]
No. CPLEX is a mixed-integer linear/quadratic solver.

You might be interested in specialized MINLP solvers:
https://github.com/JuliaOpt/KNITRO.jl
https://github.com/lanl-ansi/Juniper.jl
https://github.com/lanl-ansi/Alpine.jl

**Comment by MathematicianVogt** [comment]
Thanks for answering the question so quickly odow, and giving me references to other software. I really appreciate it!
