### ISSUE TITLE
library dependency with CPLEX version 126 on Mac OS X

### ISSUE THREAD

**Issue by chkwon** [JuliaOpt/CPLEX.jl#34]
This is the content of my CPLEX library directory on Mac OS X. CPLEX version is 12.6

```
convert
cplex
cplexamp
libcplex1260.jnilib
libcplex1260mpitransport.dylib
libcplex1260mpiworker.dylib
libcplex1260processtransport.dylib
libcplex1260processworker.dylib
libcplex1260remote.dylib
libcplex1260remotejni.jnilib
libcplex1260tcpiptransport.dylib
libcplex1260tcpipworker.dylib
```

I added `push!(libnames, "cplex")` in `build.jl` to install `CPLEX.jl`.

**Comment by joehuchette** [comment]
Is ``cplex`` a shared library? I'm guessing it's an executable. It looks like you need to [create a symlink](https://github.com/JuliaOpt/CPLEX.jl#setting-up-cplex-on-os-x-and-linux) ``libcplex1260.dylib`` that points to ``libcplex1260.jnilib``. Can you try that and try ``Pkg.build("CPLEX")`` again?

**Comment by chkwon** [comment]
@joehuchette Yes you are right; it is an executable. Creating a symlink does not work for me. Interestingly or strangely, the executable `cplex` works as a library. It installs `CPLEX.jl` and solves optimization problems. Very weird.

**Comment by chkwon** [comment]
In the [`build.jl`](https://github.com/JuliaOpt/CPLEX.jl/blob/master/deps/build.jl), I see `push!(libnames, "cplex$v")`. Is `cplex$v` also for executables?

**Comment by joehuchette** [comment]
That's there because different platforms name their shared libraries differently; I think that's just a fallback. That's interesting about the executable; my copy has all the CPLEX symbols available, and JuMP tests pass using it instead of the ``.dylib``. This might be an easier default than creating a symlink on OSX.

**Comment by joehuchette** [comment]
The only concern I have is that the external library symbols are not available (e.g. I see MKL for ``.dylib`` but not for the executable). @mlubin any idea if this is kosher?

**Comment by mlubin** [comment]
If it passes tests, go for it.

**Comment by joehuchette** [comment]
I'm more worried about performance hits than correctness.

**Comment by mlubin** [comment]
I can't come up with a reason why performance would be different. If it can't find LAPACK symbols it will crash, since Julia's LAPACK symbols don't have the same names.
