### ISSUE TITLE
be careful about version-dependent options

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/CPLEX.jl#40]
We shouldn't pretend to support a version if we didn't regenerate the options map from the corresponding header file.

**Comment by joehuchette** [comment]
a58f7155b47334c214cabf7edbb0f101316aab8f

**Comment by mlubin** [comment]
What changed?

**Comment by joehuchette** [comment]
As best I can tell, they renamed ``CPX_PARAM_*`` to ``CPXPARAM_**`` with more readable descriptions. They kept the old ones for backwards compatibility, though.

**Comment by mlubin** [comment]
Have any of the integer values changed between versions?

**Comment by joehuchette** [comment]
Don't believe so, but I'm not sure of a good way to verify without doing it exhaustively.

**Comment by mlubin** [comment]
Well unless we're sure than we can't safely support multiple versions with the same parameter list.

**Comment by joehuchette** [comment]
My random sampling technique suggests that the numbers are backwards compatible, but I can add a comment to the readme.
