### ISSUE TITLE
Problem building CPLEX

### ISSUE THREAD

**Issue by iriosu** [JuliaOpt/CPLEX.jl#41]
Hi!
I'm starting to work with JuMP and I'm trying to build and install the CPLEX package but I'm having some troubles. In particular, when I try to build the package (Pkg.build("CPLEX")) I get the error:
================================[ ERROR: CPLEX ]================================

Libdl not defined
while loading /Users/irios/.julia/v0.3/CPLEX/deps/build.jl, in expression starting on line 4

===============================================================================
I have already installed CPLEX and add it to the library PATH. I'm working on mac osx 10.9.4.
What can I do to fix it?

**Comment by mlubin** [comment]
Related to https://github.com/JuliaOpt/CPLEX.jl/commit/f9f4ca4f7088154b9354ba171feae0682ca3df1f? @joehuchette, I think Compat has a clean way to handle this.

**Comment by joehuchette** [comment]
Hmm I'm not sure why the solution in f9f4ca4f7088154b9354ba171feae0682ca3df1f isn't working here. I'll push a fix using Compat in a second.

**Comment by iriosu** [comment]
Thanks for the (amazingly fast) answer. I tried what you suggested and now I'm getting another error.
================================[ ERROR: CPLEX ]================================

None of the selected providers can install dependency libcplex.
Use BinDeps.debug(package_name) to see available providers

while loading /Users/irios/.julia/v0.3/CPLEX/deps/build.jl, in expression starting on line 35

===============================================================================

**Comment by joehuchette** [comment]
K, I just tagged a new version that (hopefully) fixes this that you can get via ``Pkg.update()`` and then ``Pkg.build("CPLEX")``. 

With your second error, the package can't find the CPLEX library. Make sure you follow [the directions here](https://github.com/JuliaOpt/CPLEX.jl#setting-up-cplex-on-os-x-and-linux) to point julia and CPLEX.jl in the right direction.

**Comment by iriosu** [comment]
Now it works. Thanks your help!
Best
