### ISSUE TITLE
"cplex.getBestObjValue()" - how to?

### ISSUE THREAD

**Issue by kaarthiksundar** [JuliaOpt/CPLEX.jl#43]
I am trying to get the best bound value after a certain termination criteria is satisfied. I looked up the documentation and source code. The JuMP documentation says I can do it using an infocallback which does not seem to work with CPLEX.jl. 

In the source code for cplex_callbacks.jl, there is a function get_best_bound, which it tried calling in my program. It throws an error "get_best_bound not defined".

**Comment by mlubin** [comment]
If you just want the bound after the solver finished, use:
```
MathProgBase.getobjbound(getInternalModel(m))
```
This is solver independent.

**Comment by kaarthiksundar** [comment]
Okay, this worked. Now, I am trying to use the infocallback as given in the JuMP documentation. 

This time I get a CPLEX error:

```
ERROR: cbgetexplorednodes not defined
CPLEX Error  1804: Calling routines from info callback.
```

The same error pops up for the rest of the fields too. 
```
ERROR: cbgetobj not defined
CPLEX Error  1804: Calling routines from info callback.
```

**Comment by joehuchette** [comment]
You should call ``getobjbound`` after optimization has completed, not inside an info callback. You should only need an info callback if you want to track these types of statistics _during_ the optimization.

**Comment by joehuchette** [comment]
e.g.
```jl
# setup mymodel here
solve(mymodel)
MathProgBase.getobjbound(getInternalModel(mymodel))
```

**Comment by kaarthiksundar** [comment]
Okay it works if I do

```
function infocallback(cb)
    node      = MathProgBase.cbgetexplorednodes(cb)
 obj       = MathProgBase.cbgetobj(cb)
 97     bestbound = MathProgBase.cbgetbestbound(cb)
 98     push!(bbdata, NodeData(node,obj,bestbound))
 99 end

**Comment by kaarthiksundar** [comment]
@joehuchette Yes, I got that. Now, I am trying to track solver progress using the infocallback; it seems to work if I do ```MathProgBase.cbgetexplorednodes(cb)``` instead of ```cbgetexplorednodes(cb)```. Why is this the case?

**Comment by joehuchette** [comment]
The MathProgBase interface functions aren't exported from the MathProgBase module, so you need to qualify them like that.

**Comment by kaarthiksundar** [comment]
It would be better to mention it in the JuMP documentation. I had to look at the source code to get it right.

**Comment by joehuchette** [comment]
Might be better just to export them, since the names get pretty verbose otherwise

**Comment by joehuchette** [comment]
So the JuMP docs were changed to use ``MathProgBase.cbgetexplorednodes(cb)`` instead of ``cbgetexplorednodes(cb)``, but for whatever reason they don't seem to have been rebuilt, sorry about that.
