### ISSUE TITLE
How to change cplex setting over multiple solves of the same model?

### ISSUE THREAD

**Issue by kaarthiksundar** [JuliaOpt/CPLEX.jl#44]
As the title suggests, I want to change eps tolerance for an MILP intially to some value, later solve some subproblem, add a cut and resolve the original model with a different tolerance. How do I go about doing this?

**Comment by joehuchette** [comment]
Try
```jl
CPLEX.set_param!(model.env, "CPX_PARAM_EPGAP", ϵ)
```
assuming your ``model::CPLEX.Model`` is already built in memory.
