### ISSUE TITLE
REPL crashing on ctrl+c?

### ISSUE THREAD

**Issue by sbebo** [JuliaOpt/CPLEX.jl#45]
I'm sure it's a known issue, but ctrl+c causes the REPL to crash (brutal segfault).
[If it only happens to me, I'd like to find out why :)]

Related: with Gurobi, ctrl+c takes me back to the REPL but the solver keeps running in the background, until it completes (or you quit the REPL) -- only marginally less annoying than a crash. Should probably open an issue there as well, if there isn't one already.

**Comment by joehuchette** [comment]
Yeah I see this as well, I mostly use CPLEX but I think I've noticed it for other solvers as well. I have pretty much no idea how to work around this though, but @mlubin maybe has some thoughts?

**Comment by mlubin** [comment]
I've seen similar issues but haven't been following the state of signal
handling in julia.
CC @tkelman @vtjnash
On Jul 30, 2015 1:02 PM, "Joey Huchette" <notifications@github.com> wrote:

Yeah I see this as well, I mostly use CPLEX but I think I've noticed it for
other solvers as well. I have pretty much no idea how to work around this
though, but @mlubin <https://github.com/mlubin> maybe has some thoughts?

—
Reply to this email directly or view it on GitHub
<https://github.com/JuliaOpt/CPLEX.jl/issues/45#issuecomment-126402564>.

**Comment by tkelman** [comment]
might need some `sigint` fiddling? ref https://github.com/JuliaLang/julia/issues/2622 and https://github.com/JuliaLang/julia/issues/12309

**Comment by joehuchette** [comment]
So just wrapping e.g.
```jl
stat = disable_sigint() do
    @cpx_ccall(mipopt, Cint, (Ptr{Void}, Ptr{Void}), model.env.ptr, model.lp)
end
```
means CPLEX just keeps running after CTRL+C, which IMO is less desirable than a brutal segfault. Ideally we'd want to propagate the SIGINT to CPLEX so it can fail gracefully, but I'm not certain how to do that.

**Comment by sbebo** [comment]
And wrapping it as in https://github.com/JuliaLang/julia/issues/12309 prevents any termination -- which is not what we want either.

The CPLEX callable library does provide a function to terminate it gracefully: http://www-01.ibm.com/support/knowledgecenter/SSSA5P_12.6.2/ilog.odms.cplex.help/refcallablelibrary/cpxapi/setterminate.html?cp=SSSA5P_12.6.2%2F2-8-0-30-2&lang=en
I wonder if it's possible to (temporarily) replace the default Julia signal handler with something that ccalls `CPXsetterminate()`. Make sense?

**Comment by sbebo** [comment]
The CPLEX callable library does provide a function to terminate it gracefully: http://www-01.ibm.com/support/knowledgecenter/SSSA5P_12.6.2/ilog.odms.cplex.help/refcallablelibrary/cpxapi/setterminate.html?cp=SSSA5P_12.6.2%2F2-8-0-30-2&lang=en
I wonder if it's possible to (temporarily) replace the default Julia signal handler with something that ccalls `CPXsetterminate()`. Make sense?

**Comment by joehuchette** [comment]
Looks like maybe we could do something like this:
```jl
try 
    @cpx_ccall(mipopt, Cint, (Ptr{Void}, Ptr{Void}), model.env.ptr, model.lp)
catch ex
    if isa(ex, InterruptException)
        @cpx_ccall(setterminate, Cint, (Ptr{Void}, Ptr{Void}), model.env.ptr, CPLEX_SIGINT)
    else
        rethrow(ex)
    end
end
```

(ref http://stackoverflow.com/questions/20831290/julia-handle-keyboard-interrupt)

**Comment by joehuchette** [comment]
I don't know what ``CPLEX_SIGINT`` should be, though.

**Comment by joehuchette** [comment]
In my not too exhaustive testing, ab715797f2d273cc3e32733b66c8e39e9407e276 seems to give the expected behavior now. Reopen if I'm wrong!
