### ISSUE TITLE
CPLEX 12.6.2 new params 

### ISSUE THREAD

**Issue by kaarthiksundar** [JuliaOpt/CPLEX.jl#48]
CPLEX 12.6.2 has introduced a bunch of new params for dealing with MISOCPs. It would be great if CPLEX.jl is updated to reflect the changes. 

Link to the new parameter list: http://www-01.ibm.com/support/knowledgecenter/SSSA5P_12.6.2/ilog.odms.cplex.help/CPLEX/Parameters/topics/introListAlpha.html

**Comment by joehuchette** [comment]
This would be good to have, but unfortunately I don't have a copy of 12.6.2 to auto generate the list in https://github.com/JuliaOpt/CPLEX.jl/blob/master/src/full_defines.jl. If you want to run ``grep "#define" cpxconst.h | awk '{ printf("const %s = convert(Cint,%s)\n",$2,$3) }'`` and send the results (or, better yet, open a PR), that'd be much appreciated.

**Comment by kaarthiksundar** [comment]
Yes, that is what I intend to do. I have auto generated the full_defines.jl file and made some manual fixes.
