### ISSUE TITLE
Failing MPB tests

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/CPLEX.jl#50]
```
ERROR: `updatemodel!` has no method matching updatemodel!(::CplexMathProgModel)
 in linprogsolvertest at /home/mlubin/.julia/v0.3/MathProgBase/test/linproginterface.jl:34
```

What was the resolution on this?

**Comment by joehuchette** [comment]
I'd like to just get rid of ``updatemodel!`` and make it the responsibility of Gurobi.jl to do the intelligent thing. Does anyone else implement this?

**Comment by mlubin** [comment]
Would be nice to not have this failing. I'm okay with removing ``updatemodel!``.

**Comment by mlubin** [comment]
``Pkg.test("CPLEX")`` is finally working
