### ISSUE TITLE
Obtaining MIP gap within LazyCallback

### ISSUE THREAD

**Issue by harshangrjn** [JuliaOpt/CPLEX.jl#51]
How do I obtain the MIPrelativegap within a lazy callback? I tried using getobjgap(m). It throws an error. I can see that the following function is implemented

     getobjgap(m::CplexMathProgModel) = get_rel_gap(m.inner)

How do I use this function to get the gap from a lazy callback ?

**Comment by mlubin** [comment]
Look at http://mathprogbasejl.readthedocs.org/en/latest/mipcallbacks.html#cbgetobj and http://mathprogbasejl.readthedocs.org/en/latest/mipcallbacks.html#cbgetbestbound
