### ISSUE TITLE
range constraint (two-sided) support 

### ISSUE THREAD

**Issue by kaarthiksundar** [JuliaOpt/CPLEX.jl#52]
When I use a two sided range constraint in a JuMP Model, I get the following warning:

```
Julia Cplex interface doesn't properly support range (two-sided) constraints.
```

Should I be concerned when this pops up?

**Comment by mlubin** [comment]
It should still be correct, but I wouldn't trust any dual values.
@joehuchette?

**Comment by joehuchette** [comment]
Yes, the duals will probably be worthless, but otherwise it should work. I haven't really stressed this code path much, though, so let me know if you run into any issues.

**Comment by odow** [comment]
Closing since we won't be fixing this. MOI+Bridges have resolved the issue from JuMP.
