### ISSUE TITLE
Incumbent Callback Error

### ISSUE THREAD

**Issue by francoisgilbert** [JuliaOpt/CPLEX.jl#53]
I am trying without success to use the incumbent callback functionality provided in JuMPfunction.jl. I get the following error on Julia 0.4:

using JuMP,CPLEX
m=Model(solver=CplexSolver(CPX_PARAM_MIPDISPLAY=5,CPX_PARAM_SCRIND=0,CPX_PARAM_REDUCE=0, CPX_PARAM_MIPCBREDLP=0))
G=1:30
T=1:5
@defVar(m,10>=y[G,T]>=0)
@defVar(m,x[G,T],Bin)
@addConstraint(m,_c[t=T],sum{y[i,t], i in G}>=100*rand()+50)
@addConstraint(m, _c[i=G,t=T],   y[i,t]<=100*x[i,t])
@setObjective(m,Min,sum{10*rand()*x[i,t]+2 *rand()*y[i,t]^2, i in G, t=T} );
function mycallback(cb)
    obj_val = cbgetnodeobjval(cb)
    if obj_val>1238.0
        rejectIncumbent(cb)
    else
        acceptIncumbent(cb)
    end
end
addIncumbentCallback(m, mycallback)
solve(m)

ERROR: MethodError: `convert` has no method matching convert(::Type{CPLEX.CplexIncumbentCallbackData}, ::CPLEX.CallbackData, ::Symbol, ::Int32, ::Array{Float64,1}, ::Ptr{Int32}, ::Ptr{Int32})
This may have arisen from a call to the constructor CPLEX.CplexIncumbentCallbackData(...),
since type constructors fall back to convert methods.
Closest candidates are:
  CPLEX.CplexIncumbentCallbackData(::CPLEX.CallbackData, ::Symbol, ::Int32, ::Array{Float64,1}, ::Ptr{Int32}, ::Ptr{Int32}, ::Array{CPLEX.BranchingChoice,1})
  CPLEX.CplexIncumbentCallbackData(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any)
  call{T}(::Type{T}, ::Any)
  ...
 in masterincumbentcallback at /Users/frank/.julia/v0.4/CPLEX/src/CplexSolverInterface.jl:653
 in optimize! at /Users/frank/.julia/v0.4/CPLEX/src/cpx_solve.jl:5
 in optimize! at /Users/frank/.julia/v0.4/CPLEX/src/CplexSolverInterface.jl:153
 in solve at /Users/frank/.julia/v0.4/JuMP/src/solvers.jl:84
 in solvehook at /Users/frank/.julia/v0.4/CPLEX/src/JuMPfunctions.jl:45
 in solve at /Users/frank/.julia/v0.4/JuMP/src/solvers.jl:62

julia> versioninfo()
Julia Version 0.4.0-dev+6819
Commit 4d72065* (2015-08-18 17:55 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.4.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by francoisgilbert** [comment]
Commenting out the last field of type CplexIncumbentCallbackData in the file CplexSolverInterface.jl will make things work at my end:

type CplexIncumbentCallbackData <: CplexCallbackData
    cbdata::CallbackData
    state::Symbol
    where::Cint
    sol::Vector{Float64}
    isfeas_p::Ptr{Cint}
    userinteraction_p::Ptr{Cint}
  #  nodes::Vector{BranchingChoice}
end

**Comment by joehuchette** [comment]
Thanks for the report and the reproducing example. I have an alternative fix I pushed in 7162aa3d0f1ffae8d37603ca5e9967563f2b502f.

**Comment by joehuchette** [comment]
(That only pushed now, since my wifi is wonky)
