### ISSUE TITLE
Readme library path is misleading in CPLEX 12.5

### ISSUE THREAD

**Issue by Thuener** [JuliaOpt/CPLEX.jl#54]
Not a issue just an enhancement. In the readme the "/path/to/CPLEX/library" path is misleading, in cplex 12.5 the real path is the bin folder (/opt/ibm/ILOG/CPLEX_Studio125/cplex/bin/x86-64_sles10_4.1). That was the only way that worked for me. I try to use /opt/ibm/ILOG/CPLEX_Studio125/cplex/lib/x86-64_sles10_4.1/static_pic/lib and didn't worked.

I suggest also to put an example:
export LD_LIBRARY_PATH="/opt/ibm/ILOG/CPLEX_Studio125/cplex/bin/x86-64_sles10_4.1":$LD_LIBRARY_PATH

**Comment by mlubin** [comment]
Good point, would you mind submitting a PR?
