### ISSUE TITLE
getsolvetime is missing

### ISSUE THREAD

**Issue by emreyamangil** [JuliaOpt/CPLEX.jl#58]
CplexMathProgModel complains that getsolvetime is not implemented, if this can be added to CPLEX.jl I would really appreciate, many thanks in advance!

**Comment by joehuchette** [comment]
Want to try out a PR? :)

**Comment by emreyamangil** [comment]
Oh god, here we go :D why not!

**Comment by emreyamangil** [comment]
I can't find a function to return time in CPLEX C API (I found cplex.getTime in C++ though), do we need to hack something to the optimize! call ourselves or is there something that we can call from CPLEX??

**Comment by mlubin** [comment]
If it's accessible from the C++ api then it's almost surely also accessible
from the C api.

**Comment by emreyamangil** [comment]
It doesn't have a clear definition but CPXgettime might do it? :) I will try it anyways!

**Comment by joehuchette** [comment]
Hopefully there's a better way, but you might have to use [cpxgettime](http://www-01.ibm.com/support/knowledgecenter/#!/SSSA5P_12.6.0/ilog.odms.cplex.help/refcallablelibrary/cpxapi/gettime.html?cp=SSSA5P_12.6.0%2F2-7-0-18-8) before and after a call to the optimizer and take the delta...

**Comment by mlubin** [comment]
http://www-01.ibm.com/support/docview.wss?uid=swg21399982
So just use tic and toq.

**Comment by mlubin** [comment]
Or safer to use ``time()``.

**Comment by joehuchette** [comment]
ugh

**Comment by mlubin** [comment]
@emreyamangil, you can add a field to ``CplexMathProgModel`` to save the execution time inside ``optimize!``

**Comment by emreyamangil** [comment]
yupp, you just answered my question!!

**Comment by mlubin** [comment]
Closed by https://github.com/JuliaOpt/CPLEX.jl/pull/59
