### ISSUE TITLE
Presolve issue for SOCPs

### ISSUE THREAD

**Issue by harshangrjn** [JuliaOpt/CPLEX.jl#60]
I have a SOCP problem (@mlubin : ACOPF with SOC relaxations), which gives different objective values when I have the following model options without any other modifications: 
a. With CPX_PARAM_PREIND=0
Opt obj: 721341.0797

b. Without CPX_PARAM_PREIND=0
Opt obj: 721299.7785

When I solve SOCP with outer approximation using callback, I still get opt obj = 721341.0797. Looks like there is an issue with having presolve switched on. 

I am on Julia 0.4 and have updated the packages. Would this be an issue on CPLEX.jl/JuMP.jl or in CPLEX itself?

**Comment by joehuchette** [comment]
This is almost certainly a (numerical?) issue with CPLEX itself. I'd recommend dumping the models to a file and reporting to CPLEX directly.

**Comment by harshangrjn** [comment]
Thanks @joehuchette. But, I couldn't figure out a way to dump the model as I can either use writeLP or writeMPS. I tried MPS and when I load it on Cplex interactive optimizer, it doesn't solve the problem to optimality. Any suggestions?

**Comment by joehuchette** [comment]
Yeah, I'm not sure what format CPLEX supports that will like you write write SOCs to file. @mlubin?

Just opening a ticket with CPLEX and asking how to send the instance seems reasonable as well.

**Comment by harshangrjn** [comment]
From the link, looks like CPLEX supports QPs to be written in MPS format. 
https://www.tu-chemnitz.de/mathematik/discrete/manuals/cplex/doc/refman/html/appendixE10.html#156840

However, when I try to write it in MPS format and load it to interactive optimizer, it is doing funny things.

**Comment by joehuchette** [comment]
Yeah, but not SOC constraints AFAICT

**Comment by mlubin** [comment]
```julia
m = Model(solver=CplexSolver())
@defVar(m, x[1:2])
@defVar(m, y >= 0)
@addConstraint(m, x[1]^2 + x[2]^2 <= y^2)
buildInternalModel(m)
MathProgBase.writeproblem(getInternalModel(m), "dump.mps")
```

**Comment by harshangrjn** [comment]
Thanks @mlubin. Will try this and keep you updated.
