### ISSUE TITLE
Cplex 12.6.3 is now available

### ISSUE THREAD

**Issue by melihozlen** [JuliaOpt/CPLEX.jl#62]
Hi,

The new Cplex version, 12.6.3, is now available. We need to add this information to build.jl for the package to build with the new version.

Cheers,

melih

**Comment by mlubin** [comment]
CPLEX tends to rename and renumber their parameters across versions, so the list of parameters needs to be regenerated and checked for breaking changes before we can safely support 12.6.3.
CC @joehuchette

**Comment by mlubin** [comment]
Might also be a good time to drop 12.4.

**Comment by joehuchette** [comment]
They didn't mention anything about parameters in the release notes, so this should be safe.
