### ISSUE TITLE
Help with CPLEX 12.6 in OS X 

### ISSUE THREAD

**Issue by mao006006** [JuliaOpt/CPLEX.jl#65]
I tried to use CPLEX.jl with JuMP. 

I have added 
export LD_LIBRARY_PATH=“Users/username/Applications/IBM/ILOG/CPLEX_Studio126/cplex/bin/x86-64_osx/”:$LD_LIBRARY_PATH

to the bash_profile. But there is no libcplexXXX.dylib file in that directory. Do I miss something here?

After Pkg.add("CPLEX"). I got the following errors:
================================[ ERROR: CPLEX ]================================

LoadError: None of the selected providers can install dependency libcplex.
Use BinDeps.debug(package_name) to see available providers

while loading /Users/username/.julia/v0.4/CPLEX/deps/build.jl, in expression starting on line 31

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: CPLEX had build errors.

 - packages with build errors remain installed in /Users/username/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("CPLEX")`
 - build a single package by running its `deps/build.jl` script

Please help me solve this problem and really appreciate it. Thank you.

**Comment by joehuchette** [comment]
``Users/username/Applications/IBM/ILOG/CPLEX_Studio126/cplex/bin/x86-64_osx/`` isn't a valid absolute path, you probably want something like ``/Users/XXXXX/Applications/IBM/ILOG/CPLEX_Studio126/cplex/bin/x86-64_osx/``, where you substitute your username in place of ``XXXXX``. Verify that the path is correct by checking the outcome from
```
ls /Users/XXXXX/Applications/IBM/ILOG/CPLEX_Studio126/cplex/bin/x86-64_osx
```
in your terminal.

**Comment by mao006006** [comment]
Thank you for your help. Yes, I used my username ( the xxxxx) there.  
    _____________________________

**Comment by mao006006** [comment]
Figured it out. Thank you.
