### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by francoisgilbert** [JuliaOpt/CPLEX.jl#68]
I am getting inconsistent results executing the following in Julia.

```
using JuMP,CPLEX
I=[1,2];
m2 = JuMP.Model(solver=CPLEX.CplexSolver());
JuMP.@defVar(m2, w[I], Bin);
JuMP.@defVar(m2, y[I] >= 0);
JuMP.@setObjective(m2, Min, 10*w[1]+w[2] + y[1] + y[2]);
JuMP.@addConstraint(m2,y[1] + 2*y[2]≤ 5*w[1]);
JuMP.@addConstraint(m2,3*y[1] + y[2]≤ 10*w[2]);
solve(m2)
```

Either the model is solved (as it should) or I get the following error:

```
ERROR: error compiling model: error compiling __CplexMathProgModel#1__: error compiling call: could not load library "/Users/frank/machinerie/IBM/ILOG/CPLEX_Studio1261/cplex/bin/x86-64_osx/libcplex1261.dylib"
dlopen(/Users/frank/machinerie/IBM/ILOG/CPLEX_Studio1261/cplex/bin/x86-64_osx/libcplex1261.dylib, 1): Symbol not found: __ZNSt8ios_base4InitD1Ev
  Referenced from: /Users/frank/machinerie/IBM/ILOG/CPLEX_Studio1261/cplex/bin/x86-64_osx/libcplex1261.dylib
  Expected in: flat namespace
 in /Users/frank/machinerie/IBM/ILOG/CPLEX_Studio1261/cplex/bin/x86-64_osx/libcplex1261.dylib
 in buildInternalModel at /Users/frank/.julia/v0.4/JuMP/src/solvers.jl:238
 in solve at /Users/frank/.julia/v0.4/JuMP/src/solvers.jl:79
```

  The error systematically occurs when I start the Julia shell session with the above instructions. I am on OSX using Julia 0.4.3. The CPLEX  deps.jl file points to libcplex1261.dylib:

> ls -l ~/machinerie/IBM/ILOG/CPLEX_Studio1261/cplex/bin/x86-64_osx/libcplex1261.dylib 
>     lrwxr-xr-x  1 frank  staff  19 Apr  7 14:17 /Users/frank/machinerie/IBM/ILOG/CPLEX_Studio1261/cplex/bin/x86-64_osx/libcplex1261.dylib -> libcplex1261.jnilib

**Comment by joehuchette** [comment]
What is the failure rate like? Is it deterministic (every session, on the first try), or not?

(edited your comment a bit for formatting)

**Comment by francoisgilbert** [comment]
Starting the julia session with the following always breaks:

|using JuMP,CPLEX I=[1,2]; m2 = JuMP.Model(solver=CPLEX.CplexSolver()); 
JuMP.@defVar(m2, w[I], Bin); JuMP.@defVar(m2, y[I] >= 0); 
JuMP.@setObjective(m2, Min, 10*w[1]+w[2] + y[1] + y[2]); 
JuMP.@addConstraint(m2,y[1] + 2*y[2]≤ 5*w[1]); 
JuMP.@addConstraint(m2,3*y[1] + y[2]≤ 10*w[2]); solve(m2)|

**Comment by joehuchette** [comment]
This looks the same as [this issue from the mailing list](https://groups.google.com/forum/#!topic/julia-opt/rpe4AroSe60). You said you have an old version of CPLEX lying around: can you try with that version to see if the same error appears?

**Comment by francoisgilbert** [comment]
Well, I installed libcplex1261 after getting the above with 
libcplex1250. Will look for something older.

Indeed, the error seems related.

**Comment by mlubin** [comment]
@francoisgilbert, could you paste the output of:
```
otool -L /Users/frank/machinerie/IBM/ILOG/CPLEX_Studio1261/cplex/bin/x86-64_osx/libcplex1261.dylib
```

**Comment by francoisgilbert** [comment]
>$ otool -L 
/Users/frank/machinerie/IBM/ILOG/CPLEX_Studio1261/cplex/bin/x86-64_osx/libcplex1261.dylib
/Users/frank/machinerie/IBM/ILOG/CPLEX_Studio1261/cplex/bin/x86-64_osx/libcplex1261.dylib:
/Users/cplexadmin/jenkins/agent-svcplexdev38/workspace/distrib-branch12.6.1/label/x64-osx.svcplexdev38/bin/x86-64_osx/static_pic/libcplex1261.jnilib 
(compatibility version 0.0.0, current version 0.0.0)

**Comment by mlubin** [comment]
@tkelman, any guess on this missing symbol issue? stdlibc++ incompatibility between Julia and CPLEX?

**Comment by tkelman** [comment]
Maybe. Dunno.

**Comment by mlubin** [comment]
@joehuchette, do we still need the ``.jnilib`` hack following https://github.com/JuliaOpt/CPLEX.jl/issues/34?

**Comment by joehuchette** [comment]
Who knows. @francoisgilbert, can you try pointing ``libcplex`` to ``/Users/frank/machinerie/IBM/ILOG/CPLEX_Studio1261/cplex/bin/x86-64_osx/cplex`` and see what happens?

**Comment by francoisgilbert** [comment]
I works! But why...

We otherwise noted that http://pkg.julialang.org/ is pointing the CPLEX 
package to tag 0.1.1 under Julia 0.4 but it's tag 0.0.19  that actually 
gets install when you do Pkg.add("CPLEX") from the julia shell (julia 
0.4.3).

**Comment by mlubin** [comment]
Could you paste the output of ``Pkg.status()``?

**Comment by francoisgilbert** [comment]
julia> Pkg.status()
20 required packages:
  - BaseTestNext                  0.2.1+             master
  - CPLEX                         0.0.19
  - Cbc                           0.1.8
  - Clp                           0.1.1
  - Conda                         0.1.9
  - ConfParser                    0.0.7
  - Dates                         0.4.4
  - Formatting                    0.1.5
  - Gadfly                        0.3.18
  - Graphs                        0.6.0
  - HDF5                          0.5.8
  - IJulia                        1.1.9
  - JLD                           0.5.9
  - JuMP                          0.10.3
  - MATLAB                        0.2.4+             master
  - MPI                           0.3.2
  - Plotly                        0.0.3
  - PyPlot                        2.1.1
  - QuantEcon                     0.3.0
  - Winston                       0.11.13
64 additional packages:
  - ArrayViews                    0.6.4
  - AutoHashEquals                0.0.9
  - BinDeps                       0.3.21
  - Blosc                         0.1.4
  - CPLEXOLD                      0.0.0-             607970e3 
(unregistered, dirty)
  - Cairo                         0.2.31
  - Calculus                      0.1.14
  - Clustering                    0.5.0
  - Codecs                        0.1.5
  - ColorTypes                    0.1.7
  - Colors                        0.5.4
  - Compat                        0.7.13
  - Compose                       0.3.18
  - Contour                       0.0.8
  - DSP                           0.0.11
  - DataArrays                    0.2.20
  - DataFrames                    0.6.10
  - DataStructures                0.3.14
  - Distances                     0.2.2
  - Distributions                 0.8.10
  - Docile                        0.5.23
  - DualNumbers                   0.1.5
  - FactCheck                     0.4.2
  - FileIO                        0.0.4
  - FixedPointNumbers             0.0.12
  - GZip                          0.2.18
  - Graphics                      0.1.3
  - Grid                          0.4.0
  - HTTPClient                    0.1.6
  - Hexagons                      0.0.4
  - Homebrew                      0.2.0
  - ImmutableArrays               0.0.11
  - IniFile                       0.2.5
  - IterationManagers             0.0.1
  - Iterators                     0.1.9
  - JSON                          0.5.0
  - KernelDensity                 0.1.2
  - LaTeXStrings                  0.1.6
  - LibCURL                       0.1.6
  - LightGraphs                   0.3.7
  - LightXML                      0.2.1
  - Loess                         0.0.6
  - MAT                           0.2.14
  - MathProgBase                  0.3.19
  - NaNMath                       0.1.1
  - Nettle                        0.2.2
  - Optim                         0.4.4
  - PDMats                        0.4.1
  - PETSc                         0.0.0-             master 
(unregistered, dirty)
  - ParserCombinator              1.7.8
  - Polynomials                   0.0.5
  - PyCall                        1.2.0
  - Reexport                      0.0.3
  - ReverseDiffSparse             0.2.11
  - SHA                           0.1.2
  - Showoff                       0.0.6
  - SortingAlgorithms             0.0.6
  - StatsBase                     0.7.4
  - StatsFuns                     0.2.0
  - Tk                            0.3.7
  - URIParser                     0.1.1
  - WoodburyMatrices              0.1.5
  - ZMQ                           0.3.1
  - Zlib                          0.1.12

julia>

**Comment by mlubin** [comment]
And ``versioninfo()``?

**Comment by francoisgilbert** [comment]
julia> versioninfo()
Julia Version 0.4.3
Commit a2f713d (2016-01-12 21:37 UTC)
Platform Info:
   System: Darwin (x86_64-apple-darwin13.4.0)
   CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
   WORD_SIZE: 64
   BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
   LAPACK: libopenblas64_
   LIBM: libopenlibm
   LLVM: libLLVM-3.3

julia>

**Comment by mlubin** [comment]
Have you run ``Pkg.update()`` recently?

**Comment by francoisgilbert** [comment]
Hum.  A few days back. Doing it now:



julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating MATLAB...
INFO: Updating BaseTestNext...
INFO: Computing changes...
INFO: Upgrading ColorTypes: v0.1.7 => v0.2.2
INFO: Upgrading Colors: v0.5.4 => v0.6.3
INFO: Installing Combinatorics v0.2.0
INFO: Upgrading Compose: v0.3.18 => v0.4.2
INFO: Upgrading Contour: v0.0.8 => v0.1.0
INFO: Upgrading DataFrames: v0.6.10 => v0.7.0
INFO: Upgrading DataStructures: v0.3.14 => v0.4.3
INFO: Upgrading Distances: v0.2.2 => v0.3.0
INFO: Upgrading DualNumbers: v0.1.5 => v0.2.2
INFO: Upgrading FixedPointNumbers: v0.0.12 => v0.1.2
INFO: Installing FixedSizeArrays v0.0.10
INFO: Upgrading Gadfly: v0.3.18 => v0.4.2
INFO: Upgrading HTTPClient: v0.1.6 => v0.2.0
INFO: Upgrading LibCURL: v0.1.6 => v0.2.0
INFO: Upgrading LightGraphs: v0.3.7 => v0.5.2
INFO: Upgrading MPI: v0.3.2 => v0.4.0
INFO: Installing MacroTools v0.3.0
INFO: Installing Measures v0.0.2
INFO: Upgrading NaNMath: v0.1.1 => v0.2.1
INFO: Upgrading PyCall: v1.2.0 => v1.4.0
INFO: Upgrading QuantEcon: v0.3.0 => v0.4.2
INFO: Installing Requires v0.2.2
INFO: Upgrading ReverseDiffSparse: v0.2.11 => v0.3.0
INFO: Upgrading StatsBase: v0.7.4 => v0.8.0
INFO: Upgrading URIParser: v0.1.1 => v0.1.3
INFO: Removing FactCheck v0.4.2
INFO: Removing ImmutableArrays v0.0.11
INFO: Removing IterationManagers v0.0.1
INFO: Removing MAT v0.2.14
INFO: Removing Zlib v0.1.12
INFO: Building LibCURL
INFO: Recompiling stale cache file 
/Users/frank/.julia/lib/v0.4/BinDeps.ji for module BinDeps.
INFO: Recompiling stale cache file 
/Users/frank/.julia/lib/v0.4/URIParser.ji for module URIParser.
INFO: Recompiling stale cache file /Users/frank/.julia/lib/v0.4/SHA.ji 
for module SHA.
INFO: Building Homebrew
INFO: Recompiling stale cache file /Users/frank/.julia/lib/v0.4/JSON.ji 
for module JSON.
HEAD is now at 53c5089 CoreTap#install: fix clone target setting
HEAD is now at d45fe22 Merge pull request #91 from staticfloat/staging
INFO: Building Blosc
INFO: Building HDF5
INFO: Building LightXML
INFO: Building MPI
INFO: Attempting to Create directory /Users/frank/.julia/v0.4/MPI/deps/build
INFO: Changing Directory to /Users/frank/.julia/v0.4/MPI/deps/build
-- The Fortran compiler identification is GNU 5.2.0
-- The C compiler identification is AppleClang 6.1.0.6020053
-- Checking whether Fortran compiler has -isysroot
-- Checking whether Fortran compiler has -isysroot - yes
-- Checking whether Fortran compiler supports OSX deployment target flag
-- Checking whether Fortran compiler supports OSX deployment target flag 
- yes
-- Check for working Fortran compiler: /usr/local/bin/gfortran
-- Check for working Fortran compiler: /usr/local/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/local/bin/gfortran supports Fortran 90
-- Checking whether /usr/local/bin/gfortran supports Fortran 90 -- yes
-- Check for working C compiler: 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc 
-- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Git: 
/Applications/Julia-0.4.3.app/Contents/Resources/julia/libexec/git-core/git 
(found version "1.8.5.6")
-- Found MPI_C: /usr/local/Cellar/open-mpi/1.8.6/lib/libmpi.dylib
-- Found MPI_Fortran: 
/usr/local/Cellar/open-mpi/1.8.6/lib/libmpi_usempif08.dylib;/usr/local/Cellar/open-mpi/1.8.6/lib/libmpi_usempi_ignore_tkr.a;/usr/local/Cellar/open-mpi/1.8.6/lib/libmpi_mpifh.dylib;/usr/local/Cellar/open-mpi/1.8.6/lib/libmpi.dylib 

-- Detecting Fortran/C Interface
-- Detecting Fortran/C Interface - Found GLOBAL and MODULE mangling
-- Looking for MPI_Comm_c2f
-- Looking for MPI_Comm_c2f - found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/frank/.julia/v0.4/MPI/deps/build
Scanning dependencies of target gen_constants
[ 12%] Building Fortran object 
CMakeFiles/gen_constants.dir/gen_constants.f90.o
[ 25%] Linking Fortran executable gen_constants
[ 25%] Built target gen_constants
Scanning dependencies of target version
[ 25%] Built target version
Scanning dependencies of target gen_functions
[ 37%] Building C object CMakeFiles/gen_functions.dir/gen_functions.c.o
[ 50%] Linking C executable gen_functions
[ 50%] Built target gen_functions
Scanning dependencies of target mpijl-build
[ 62%] Generating mpi-build.jl
[ 62%] Built target mpijl-build
Scanning dependencies of target mpijl
[ 75%] Generating compile-time.jl
[ 75%] Built target mpijl
Scanning dependencies of target juliampi
[ 87%] Building Fortran object CMakeFiles/juliampi.dir/test_mpi.f90.o
[100%] Linking Fortran shared library libjuliampi.dylib
[100%] Built target juliampi
[ 25%] Built target gen_constants
[ 25%] Built target version
[ 50%] Built target gen_functions
[ 62%] Built target mpijl-build
[ 75%] Built target mpijl
[100%] Built target juliampi
Install the project...
-- Install configuration: ""
-- Installing: /Users/frank/.julia/v0.4/MPI/deps/src/./compile-time.jl
-- Installing: /Users/frank/.julia/v0.4/MPI/deps/usr/lib/libjuliampi.dylib
INFO: Building PyCall
INFO: Recompiling stale cache file /Users/frank/.julia/lib/v0.4/Conda.ji 
for module Conda.
INFO: PyCall is using /usr/local/opt/python/bin/python2.7 (Python 
2.7.10) at /usr/local/opt/python/bin/python2.7, libpython = 
/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Python

julia>

**Comment by mlubin** [comment]
Remove the ``CPLEXOLD`` directory. It is blocking the updates.

**Comment by francoisgilbert** [comment]
So this was all my fault. After update:

julia> Pkg.status()
20 required packages:
  - BaseTestNext                  0.2.1+             master
  - CPLEX                         0.1.1
  - Cbc                           0.2.0
  - Clp                           0.2.0
  - Conda                         0.1.9
  - ConfParser                    0.0.7
  - Dates                         0.4.4

**Comment by tkelman** [comment]
That's really odd that having an unregistered, dirty copy of a package prevents Pkg from updating the real thing. Sounds like it might be a bug.

**Comment by mlubin** [comment]
My guess is that there was an upper bound on MPB in requires.
On Apr 14, 2016 4:25 PM, "Tony Kelman" <notifications@github.com> wrote:

That's really odd that having an unregistered, dirty copy of a package
prevents Pkg from updating the real thing. Sounds like it might be a bug.

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/JuliaOpt/CPLEX.jl/issues/68#issuecomment-210134044>

**Comment by tkelman** [comment]
Oh good call, that does sound likely. Having one package with a restrictive upper bound holds back everything. This is probably the main use case I can think of where something virtualenv-like (or just setting JULIA_PKGDIR on a per-project basis) would fix matters.

**Comment by frknndrr** [comment]
Hello everyone,

I am having the similar problems with Pkg.build("CPLEX"). So far I have tried:

1. Creating a symlink to "cplex"
2. Creating a symlink to "libcplex1263.jnilib"
3. Adding push!(libnames, "cplex") in build.jl of CPLEX package
4. Adding push!(libnames, "libcplex1263.jnilib") in build.jl

None of these work. Is there anything I can do to solve this issue?

Thank you in advance!

**Comment by odow** [comment]
Closing as stale. The new Pkg environments fix this.
