### ISSUE TITLE
Building package

### ISSUE THREAD

**Issue by Thuener** [JuliaOpt/CPLEX.jl#70]
Using using CPLEX_Studio1263, Julia 0.4.5 and Ubuntu 16.04:

Pkg.add("CPLEX")
INFO: Installing CPLEX v0.1.2
INFO: Building CPLEX

signal (11): Segmentation fault
strlen at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
__strdup at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
jl_uv_dlopen at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
check_path! at /home/thuener/.julia/v0.4/BinDeps/src/dependencies.jl:559
ERROR: Build process failed.
 in build! at ./pkg/entry.jl:701
 [inlined code] from ./task.jl:422
 in add at ./pkg/entry.jl:64

**Comment by joehuchette** [comment]
Based on the backtrace, it appears this an issue that should be raised with [BinDeps](https://github.com/JuliaLang/BinDeps.jl), not here.

**Comment by Thuener** [comment]
The strange thing is that this error only occurs with CPLEX_Studio1263, with CPLEX_Studio1251 works fine. I don't know for sure that is a problem with BinDeps, but I will close the issue.
