### ISSUE TITLE
cpx_solve.jl:257 ERROR: LoadError: KeyError: 12 not found

### ISSUE THREAD

**Issue by Thuener** [JuliaOpt/CPLEX.jl#72]
The status code for CPX_STAT_ABORT_OBJ_LIM(Aborted due to an objective limit) is mapped to 11 instead of 12.  
https://www.tu-chemnitz.de/mathematik/discrete/manuals/cplex/doc/refman/html/appendixB.html

**Comment by mlubin** [comment]
What version of CPLEX are you using?

**Comment by Thuener** [comment]
12.5.1.0
