### ISSUE TITLE
Erro in CPLEX call

### ISSUE THREAD

**Issue by AlaaAlameer85** [JuliaOpt/CPLEX.jl#74]
Hallo, I am trying to use CPLEX callback, however I am gettint the following error 
`convert` has no method matching convert(::Type{Ptr{Float64}}, ::Array{Float64,1})
This may have arisen from a call to the constructor Ptr{Float64}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{Ptr{T}}, !Matched::UInt64)
  convert{T}(::Type{Ptr{T}}, !Matched::Int64)
  ...
any ideas?? 
Thanks a lot

**Comment by mlubin** [comment]
Could you provide a standalone example that reproduces this error?

**Comment by AlaaAlameer85** [comment]
Actually I solved the issue it seems some CPLEX version compatibility issues. 

I came also across another issue, is setLazyCallback is replaced with addLazyCallback??
when I used the first one it gave me an error, however addLazyCallback works fine.

**Comment by mlubin** [comment]
Yes, ``setLazyCallback`` was renamed to ``addLazyCallback`` in [February 2015](https://github.com/JuliaOpt/JuMP.jl/blob/master/NEWS.md#version-080-february-17-2015), and then to ``addlazycallback`` in [April](https://github.com/JuliaOpt/JuMP.jl/blob/master/NEWS.md#version-0130-april-29-2016) this year. If you see any online material using the old names, please let the author know so they can correct it.
