### ISSUE TITLE
solving twice gives different objective values

### ISSUE THREAD

**Issue by IssamT** [JuliaOpt/CPLEX.jl#76]
I was solving a model, modifying the objective function, and solving it again using JuMP and CPLEX.
The first time it is solved to optimality while the second time it is unfeasible.

I tried to find out where is the problem and I managed to reduce the model to a very simple one, and solving the latter twice on row gives the correct result on the first solve but a wrong result on the second solve ( without modifying anything in the model). 

This bug does not happen when using other solvers like CbcSolver

Also it doesn't happen if I write the  testmodel.lp and solve it twice on row using the standalone cplex binary (which means the problem isn't from the warm start of cplex)

```
using JuMP
using Cbc
using CPLEX

function test_model(C::Float64)
    mcs = Model(solver = CplexSolver())

    @variable(mcs, 0 <= z <= 100, Int)
    @variable(mcs, b[1:10], Bin)
    @constraint(mcs, roundconstr ,
      0 <= z - sum{0.5 * b[u], u in 1:10}/C <= 0.999)
    @objective(mcs, Max, z - sum{0.5 * b[u], u in 1:3}/C)

    print("FIRST SOLVE")
    solve(mcs)
    @show getobjectivevalue(mcs)
    print("SECOND SOLVE")
    solve(mcs)
    @show getobjectivevalue(mcs)
end

test_model(40.0)
```

**Comment by IssamT** [comment]
julia> Pkg.status()

11 required packages:
 - Atom                          0.4.4
 - AutoHashEquals                0.0.10             master
 - Blosc                         0.1.6+             master
 - CPLEX                         0.1.3+             master
 - Cbc                           0.2.3
 - Clp                           0.2.2
 - FactCheck                     0.4.3              master
 - Graphs                        0.6.0
 - IJulia                        1.2.0
 - JuMP                          0.14.0+            master
 - LightGraphs                   0.6.1              414f14d8 (dirty)
53 additional packages:
 - BinDeps                       0.4.2
 - Blink                         0.3.4
 - Calculus                      0.1.15
 - Clustering                    0.6.0+             master
 - CodeTools                     0.3.1
 - Codecs                        0.2.0
 - Compat                        0.8.6
 - Conda                         0.2.3
 - DataStructures                0.4.5
 - Devectorize                   0.4.2              master
 - Distances                     0.3.2+             master
 - Distributions                 0.10.2
 - Docile                        0.5.23
 - FileIO                        0.1.0
 - ForwardDiff                   0.2.2
 - GZip                          0.2.20
 - GraphMatrices                 0.1.0
 - HDF5                          0.6.5
 - Hiccup                        0.0.3
 - HttpCommon                    0.2.6
 - HttpParser                    0.1.1
 - HttpServer                    0.1.6
 - JLD                           0.6.3
 - JSON                          0.6.0
 - JuliaParser                   0.6.4
 - LNR                           0.0.2
 - Lazy                          0.11.0
 - LegacyStrings                 0.1.1
 - LightXML                      0.3.0
 - MacroTools                    0.3.2
 - MathProgBase                  0.5.2
 - MatrixDepot                   0.5.6
 - MbedTLS                       0.3.0
 - Media                         0.2.1
 - Mustache                      0.0.15
 - Mux                           0.2.1
 - NaNMath                       0.2.1
 - NearestNeighbors              0.0.4
 - Nettle                        0.2.3
 - PDMats                        0.4.2
 - ParserCombinator              1.7.9
 - Reexport                      0.0.3
 - Requires                      0.2.2
 - ReverseDiffSparse             0.5.8
 - Rmath                         0.1.2
 - SHA                           0.2.1
 - StatsBase                     0.9.0
 - StatsFuns                     0.3.0
 - URIParser                     0.1.6
 - WebSockets                    0.2.1
 - ZMQ                           0.3.4

**Comment by IssamT** [comment]
FIRST SOLVE
WARNING: Julia Cplex interface doesn't properly support range (two-sided) constraints.

Root node processing (before b&c):
  Real time             =    0.00 sec. (0.03 ticks)
Parallel b&c, 4 threads:
  Real time             =    0.00 sec. (0.00 ticks)
  Sync time (average)   =    0.00 sec.
  Wait time (average)   =    0.00 sec.
                          ------------
Total (root+branch&cut) =    0.00 sec. (0.03 ticks)
Found incumbent of value 0.000000 after 0.00 sec. (0.00 ticks)
Tried aggregator 1 time.
MIP Presolve eliminated 0 rows and 8 columns.
Reduced MIP has 1 rows, 4 columns, and 4 nonzeros.
Reduced MIP has 1 binaries, 2 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.00 sec. (0.01 ticks)
Probing time = 0.00 sec. (0.00 ticks)
Tried aggregator 1 time.
Reduced MIP has 1 rows, 4 columns, and 4 nonzeros.
Reduced MIP has 1 binaries, 2 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.00 sec. (0.00 ticks)
Probing time = 0.00 sec. (0.00 ticks)
MIP emphasis: balance optimality and feasibility.
MIP search method: dynamic search.
Parallel mode: deterministic, using up to 4 threads.
Root relaxation solution time = 0.00 sec. (0.00 ticks)

        Nodes                                         Cuts/
   Node  Left     Objective  IInf  Best Integer    Best Bound    ItCnt     Gap

*     0+    0                            0.0000        1.0000              --- 
*     0     0      integral     0        1.0000        1.0000        0    0.00%
Elapsed time = 0.01 sec. (0.02 ticks, tree = 0.00 MB, solutions = 2)
getobjectivevalue(mcs) = 1.0
SECOND SOLVE
Root node processing (before b&c):
  Real time             =    0.01 sec. (0.03 ticks)
Parallel b&c, 4 threads:
  Real time             =    0.00 sec. (0.00 ticks)
  Sync time (average)   =    0.00 sec.
  Wait time (average)   =    0.00 sec.
                          ------------
Total (root+branch&cut) =    0.01 sec. (0.03 ticks)
Presolve time = 0.00 sec. (0.00 ticks)
Warning:  No solution found from 3 MIP starts.
Retaining values of one MIP start for possible repair.
Found incumbent of value 1.987500 after 0.00 sec. (0.01 ticks)
Tried aggregator 1 time.
MIP Presolve eliminated 0 rows and 8 columns.
Reduced MIP has 1 rows, 4 columns, and 4 nonzeros.
Reduced MIP has 0 binaries, 3 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.00 sec. (0.01 ticks)
Tried aggregator 1 time.
Reduced MIP has 1 rows, 4 columns, and 4 nonzeros.
Reduced MIP has 0 binaries, 3 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.00 sec. (0.00 ticks)
MIP emphasis: balance optimality and feasibility.
MIP search method: dynamic search.
Parallel mode: deterministic, using up to 4 threads.
Root relaxation solution time = 0.00 sec. (0.00 ticks)

        Nodes                                         Cuts/
   Node  Left     Objective  IInf  Best Integer    Best Bound    ItCnt     Gap

*     0+    0                            1.9875        2.0000             0.63%
*     0     0      integral     0        2.0000        2.0000        0    0.00%
Elapsed time = 0.00 sec. (0.03 ticks, tree = 0.00 MB, solutions = 2)
getobjectivevalue(mcs) = 2.0

**Comment by mlubin** [comment]
Thanks for the report. If nobody else is motivated to fix this, your options are to:

1. Not use two-sided constraints (as the warning says, they're broken in cplex)
2. Roll up your sleeves and debug and fix the issue
3. Let IBM know that there's demand for them to maintain a Julia interface

**Comment by IssamT** [comment]
Thanks for the hint. Indeed splitting the two sided constraint solves the issue. I had thought that the problem with the two-sided constraints was only the dual values being irrelevant...

**Comment by odow** [comment]
Without spending too much time going into this, my guess is that the old interface incorrectly handled the resetting of the RHS vector on the resolve of JuMP. I've added a test in MathOptInterface with this example. The MOI rewrite now correctly (I think) handles ranged constraints via the `Interval` set.
