### ISSUE TITLE
error thrown from mipopt

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/CPLEX.jl#81]
When using CPLEX through Pajarito with callbacks, I'm seeing:

```
ERROR: LoadError: CPLEX.CplexError(1217,"CPLEX Error  1217: No solution exists.\n")
 in optimize! at /home/mlubin/.julia/v0.4/CPLEX/src/cpx_solve.jl:11
 in optimize! at /home/mlubin/.julia/v0.4/CPLEX/src/CplexSolverInterface.jl:156
 in solve at /home/mlubin/.julia/v0.4/JuMP/src/solvers.jl:141
```

Which means that this [line](https://github.com/JuliaOpt/CPLEX.jl/blob/35d24569d400c810ca1119e339c5cf090cc07cd5/src/cpx_solve.jl#L4) is throwing an error. Any idea why cplex is doing this instead of just returning infeasible status?

CC @chriscoey

**Comment by joehuchette** [comment]
That's strange. Presumably there's a separate call into CPLEX that's failing since the model is infeasible and no solution exists? Not sure where, though.

**Comment by mlubin** [comment]
Well the stranger part is that the model isn't supposed to be infeasible. But @chriscoey and I will do some digging.
