### ISSUE TITLE
Cplex throws error for a feasible MILP problem instance

### ISSUE THREAD

**Issue by kaarthiksundar** [JuliaOpt/CPLEX.jl#84]
The following error is thrown for an MILP problem instance that is feasible ``CPLEX.CplexError(1217,"CPLEX Error  1217: No solution exists.\n")``

Any help is appreciated.

**Comment by mlubin** [comment]
Write the problem to MPS or LP format and confirm that CPLEX still reports infeasible. If so, send the instance to IBM with a feasible solution.

**Comment by kaarthiksundar** [comment]
Is there a way to do that when callbacks are being used?

**Comment by mlubin** [comment]
Nope. You can record all of the cuts you add in the callbacks and create a new standalone instance.

**Comment by kaarthiksundar** [comment]
I had to switch of the presolver as I was using the lazy callback.

**Comment by mlubin** [comment]
You shouldn't have to switch off the presolver to use callbacks.

**Comment by kaarthiksundar** [comment]
This is a known issue I have faced with CPLEX. It tends to presolve out variables that are being used in the lazy callbacks. This does not happen with Gurobi.

**Comment by mlubin** [comment]
There may be an option that tells it not to do that.
